package data {
    import flash.filesystem.File;
    import flash.filesystem.FileStream;
    import flash.filesystem.FileMode;
    import Bezel.Logger;

    /**
     * ServerData — All data received from the Archipelago server during the
     * Connected packet. Can be loaded from logic.json and supplemented by slot_data.
     */
    public class ServerData {
        // Item Mapping (from slot_data)
        public var tokenMap:Object;              // apId (str) → stage str_id
        public var tokenStages:Object;           // stage str_id → true (reverse index)
        public var talismanMap:Object;           // apId (str) → "seed/rarity/type/upgradeLevel"
        public var talismanNameMap:Object;       // apId (str) → display name
        public var shadowCoreMap:Object;         // apId (str) → amount (int)
        public var shadowCoreNameMap:Object;     // apId (str) → display name
        public var wizStashTalData:Object;       // stage str_id → "seed/rarity/type/upgradeLevel"

        // ID Mappings (from itemdata.json)
        public var apIdToGameId:Object;          // AP ID (int) → game ID (int) — skills, traits, gems, mapTiles
        public var apIdToName:Object;            // AP ID (int) → display name (str) — all named items
        public var stagesByStrId:Object;         // strId → { itemApId, locApId, wizStashLocApId, type }
        public var stagesByLocApId:Object;       // locApId (int) → stage strId — for location lookups
        public var talismansByApId:Object;       // item AP ID (int) → { str_id, tal_data }
        public var shadowCoresByApId:Object;     // item AP ID (int) → { str_id, amounts, total }

        // Logic Rules (from logic.json — generated by py-scripts/generate_logic_json.py)
        public var stageSkills:Object;           // stage str_id → Array<WIZLOCK skill string e.g. "gemSkills: 2">
        public var stageRequirements:Object;     // stage str_id → Array<requirement string>
                                                 //   "Field_<sid>": prereq stage's field token (OR-combined)
                                                 //   "talismanRow:N" / "talismanColumn:N" / "skillPoints:N" / etc.
                                                 //     (AND-combined alongside the Field_ subset)
        public var stageWaveCount:Object;        // stage str_id → wave count (int)
        public var stageAvailableGems:Object;    // stage str_id → Array<gem type names>
        public var stageUnlocks:Object;          // stage str_id → Array<down-stream str_ids> (vanilla overworld map)
        public var freeStages:Array;             // Array of stage str_ids without field tokens (W1-W4)
        public var matchingTalismans:Object;     // { grid:[apId*9], rows:[[apId*3]*3], columns:[[apId*3]*3] }

        // Game Options (from slot_data)
        public var serverOptions:ServerOptions;

        private var _logger:Logger;

        public function ServerData(logger:Logger = null) {
            _logger = logger;
            initialize();
        }

        public function initialize():void
        {
            tokenMap = {};
            tokenStages = {};
            talismanMap = {};
            talismanNameMap = {};
            shadowCoreMap = {};
            shadowCoreNameMap = {};
            wizStashTalData = {};
            apIdToGameId = {};
            apIdToName = {};
            stagesByStrId = {};
            stagesByLocApId = {};
            talismansByApId = {};
            shadowCoresByApId = {};
            stageSkills = {};
            stageRequirements = {};
            stageWaveCount = {};
            stageAvailableGems = {};
            stageUnlocks = {};
            freeStages = [];
            matchingTalismans = null;
            serverOptions = new ServerOptions();
        }

        /**
         * Load item data from embedded itemdata.json (compiled into SWF).
         * Populates AP ID to game name mappings (skills, traits, stages, talismans, etc.).
         */
        public function loadItemDataFromJSON():void
        {
            try
            {
                // Load from embedded data (compiled into SWF, not external file)
                var rawData:String = EmbeddedData.getItemDataJSON();
                var itemData:Object = JSON.parse(rawData);

                // Skills: AP ID 300-323 → game ID 0-23
                if (itemData.skills)
                {
                    for each (var skill:Object in itemData.skills)
                    {
                        apIdToGameId[skill.ap_id] = skill.game_id;
                        apIdToName[skill.ap_id] = skill.name;
                    }
                }

                // Battle traits: AP ID 400-414 → game ID 0-14
                if (itemData.battleTraits)
                {
                    for each (var trait:Object in itemData.battleTraits)
                    {
                        apIdToGameId[trait.ap_id] = trait.game_id;
                        apIdToName[trait.ap_id] = trait.name;
                    }
                }

                // Gem unlocks: AP ID 600-605 → game ID 0-5
                if (itemData.gemUnlocks)
                {
                    for each (var gem:Object in itemData.gemUnlocks)
                    {
                        apIdToGameId[gem.ap_id] = gem.game_id;
                        apIdToName[gem.ap_id] = gem.name;
                    }
                }

                // Map tiles: AP ID 200-225 → game ID 0-25
                if (itemData.mapTiles)
                {
                    for each (var tile:Object in itemData.mapTiles)
                    {
                        apIdToGameId[tile.ap_id] = tile.game_id;
                    }
                }

                // Stages: strId → AP IDs, and locApId → strId for location lookups
                if (itemData.stages)
                {
                    for each (var stage:Object in itemData.stages)
                    {
                        var stageEntry:Object = {
                            strId:          stage.strId,
                            type:           stage.type,
                            itemApId:       stage.itemApId,
                            locApId:        stage.locApId,
                            wizStashLocApId: stage.wizStashLocApId
                        };
                        stagesByStrId[stage.strId] = stageEntry;
                        if (stage.locApId != null)
                        {
                            stagesByLocApId[stage.locApId] = stage.strId;
                        }
                        if (stage.itemApId != null)
                        {
                            apIdToName[stage.itemApId] = stage.strId + " Field Token";
                        }
                    }
                }

                // Talisman fragments: item AP ID 700-799 → {str_id, tal_data}
                if (itemData.talismanFragments)
                {
                    for each (var talisman:Object in itemData.talismanFragments)
                    {
                        talismansByApId[talisman.item_ap_id] = {
                            strId:   talisman.str_id,
                            talData: talisman.tal_data
                        };
                        apIdToName[talisman.item_ap_id] = "Talisman Fragment (" + talisman.str_id + ")";
                    }
                }

                // Extra talisman fragments
                if (itemData.extraTalismanFragments)
                {
                    for each (var extraTalisman:Object in itemData.extraTalismanFragments)
                    {
                        talismansByApId[extraTalisman.item_ap_id] = {
                            strId:   extraTalisman.str_id,
                            talData: extraTalisman.tal_data
                        };
                        apIdToName[extraTalisman.item_ap_id] = "Talisman Fragment (" + extraTalisman.str_id + ")";
                    }
                }

                // Build talismanMap (apId str → talData str) from talismansByApId.
                for (var talApId:String in talismansByApId)
                {
                    var talEntry:Object = talismansByApId[talApId];
                    if (talEntry != null && talEntry.talData != null)
                    {
                        talismanMap[talApId] = String(talEntry.talData);
                    }
                }

                // Shadow core stashes: item AP ID 800-868 → {str_id, amounts, total}
                if (itemData.shadowCoreStashes)
                {
                    for each (var shadowCore:Object in itemData.shadowCoreStashes)
                    {
                        shadowCoresByApId[shadowCore.item_ap_id] = {
                            strId:   shadowCore.str_id,
                            amounts: shadowCore.amounts,
                            total:   shadowCore.total
                        };
                        apIdToName[shadowCore.item_ap_id] = shadowCore.total + " Shadow Cores (" + shadowCore.str_id + ")";
                    }
                }

                // Extra shadow core stashes
                if (itemData.extraShadowCoreStashes)
                {
                    for each (var extraShadowCore:Object in itemData.extraShadowCoreStashes)
                    {
                        shadowCoresByApId[extraShadowCore.item_ap_id] = {
                            strId:   extraShadowCore.str_id,
                            amounts: extraShadowCore.amounts,
                            total:   extraShadowCore.total
                        };
                        apIdToName[extraShadowCore.item_ap_id] = extraShadowCore.total + " Shadow Cores (" + extraShadowCore.str_id + ")";
                    }
                }

                if (_logger)
                {
                    _logger.log("ServerData", "Loaded itemdata.json — "
                        + _countKeys(apIdToGameId) + " ID mappings, "
                        + _countKeys(stagesByStrId) + " stages, "
                        + _countKeys(talismansByApId) + " talismans, "
                        + _countKeys(shadowCoresByApId) + " shadow core stashes");
                }
            }
            catch (e:Error)
            {
                if (_logger)
                {
                    _logger.log("ServerData", "ERROR loading itemdata.json: " + e.message);
                }
            }
        }

        /**
         * Load logic rules from embedded logic.json (compiled into SWF).
         *
         * Populates per-stage WIZLOCK skill requirements, the new requirements
         * list (Field_<sid> prereqs + talismanRow/talismanColumn/skillPoints
         * counter gates), wave counts, and the matching-talisman 3x3 grid for
         * talismanRow/Column achievement evaluation.
         *
         * The JSON is generated from apworld data by
         *   do not commit/py-scripts/generate_logic_json.py
         * so the apworld remains the single source of truth.
         */
        public function loadLogicFromJSON():void
        {
            try
            {
                var rawData:String = EmbeddedData.getLogicDataJSON();
                var logicData:Object = JSON.parse(rawData);

                if (logicData.stages)
                {
                    for each (var stageLogic:Object in logicData.stages)
                    {
                        var strId:String = stageLogic.strId;
                        if (stageLogic.requiredSkills)
                            stageSkills[strId] = stageLogic.requiredSkills;
                        if (stageLogic.requirements)
                            stageRequirements[strId] = stageLogic.requirements;
                        if (stageLogic.waveCount !== undefined)
                            stageWaveCount[strId] = int(stageLogic.waveCount);
                        if (stageLogic.availableGems)
                            stageAvailableGems[strId] = stageLogic.availableGems;
                        if (stageLogic.unlocks)
                            stageUnlocks[strId] = stageLogic.unlocks;
                    }
                }

                // freeStages comes from slot_data.free_stages (per-seed,
                // depends on the starting_stage yaml option). Set by
                // ApReceiver.handleConnected before this function runs;
                // do NOT overwrite it from logic.json.

                if (logicData.matchingTalismans)
                    matchingTalismans = logicData.matchingTalismans;

                if (_logger)
                {
                    var nReq:int = 0;
                    for (var s:String in stageRequirements) nReq++;
                    _logger.log("ServerData", "Loaded logic.json — "
                        + nReq + " stages with requirements, "
                        + (matchingTalismans != null ? "matching talismans loaded" : "no matching talismans"));
                }
            }
            catch (e:Error)
            {
                if (_logger)
                {
                    _logger.log("ServerData", "ERROR loading logic.json: " + e.message);
                }
            }
        }

        public function clear():void
        {
            initialize();
        }

        private static function _countKeys(obj:Object):int {
            var n:int = 0;
            for (var k:String in obj) n++;
            return n;
        }
    }
}
