"""
GemCraft Frostborn Wrath — Level Progression Rules

Defines all 122 game stages and their unlock requirements.
Includes free stages (W1-W4) through endgame (A1-A6).
"""

from .rulesdata_settings import WAVE_TIERS

# =====================================================================
# LEVEL REQUIREMENTS - All 122 stages
# =====================================================================
# Each stage defines:
#   - tier: Stage progression tier (0-12)
#   - wave_count: Number of waves in this stage
#   - required_skills: WIZLOCK skills needed to play
#   - unlock_requirements: What must be unlocked to access this stage
#
level_requirements = {
    "A1": {
        "type": "NORMAL",
        "wave_count": 90,
        "tier": 11,
        "required_skills": [],
    },
    "A2": {
        "type": "NORMAL",
        "wave_count": 90,
        "tier": 11,
        "required_skills": [],
    },
    "A3": {
        "type": "NORMAL",
        "wave_count": 90,
        "tier": 11,
        "required_skills": [],
    },
    "A4": {
        "type": "NORMAL",
        "wave_count": 100,
        "tier": 12,
        "required_skills": [],
    },
    "A5": {
        "type": "NORMAL",
        "wave_count": 96,
        "tier": 12,
        "required_skills": [],
    },
    "A6": {
        "type": "NORMAL",
        "wave_count": 99,
        "tier": 12,
        "required_skills": [],
    },
    "B1": {
        "type": "NORMAL",
        "wave_count": 76,
        "tier": 9,
        "required_skills": [],
    },
    "B2": {
        "type": "NORMAL",
        "wave_count": 80,
        "tier": 10,
        "required_skills": [],
    },
    "B3": {
        "type": "NORMAL",
        "wave_count": 86,
        "tier": 11,
        "required_skills": [],
    },
    "B4": {
        "type": "NORMAL",
        "wave_count": 80,
        "tier": 10,
        "required_skills": [],
    },
    "B5": {
        "type": "SECRET",
        "wave_count": 84,
        "tier": 11,
        "required_skills": [],
    },
    "C1": {
        "type": "NORMAL",
        "wave_count": 82,
        "tier": 10,
        "required_skills": [],
    },
    "C2": {
        "type": "NORMAL",
        "wave_count": 80,
        "tier": 10,
        "required_skills": [],
    },
    "C3": {
        "type": "NORMAL",
        "wave_count": 84,
        "tier": 11,
        "required_skills": [],
    },
    "C4": {
        "type": "TILE_GIVING",
        "wave_count": 87,
        "tier": 11,
        "required_skills": [],
    },
    "C5": {
        "type": "EPIC",
        "wave_count": 90,
        "tier": 11,
        "required_skills": [],
    },
    "D1": {
        "type": "NORMAL",
        "wave_count": 72,
        "tier": 9,
        "required_skills": [],
    },
    "D2": {
        "type": "NORMAL",
        "wave_count": 75,
        "tier": 9,
        "required_skills": [],
    },
    "D3": {
        "type": "EPIC",
        "wave_count": 77,
        "tier": 9,
        "required_skills": [],
    },
    "D4": {
        "type": "NORMAL",
        "wave_count": 70,
        "tier": 8,
        "required_skills": [],
    },
    "D5": {
        "type": "NORMAL",
        "wave_count": 78,
        "tier": 10,
        "required_skills": [],
    },
    "E1": {
        "type": "NORMAL",
        "wave_count": 70,
        "tier": 8,
        "required_skills": [],
    },
    "E2": {
        "type": "NORMAL",
        "wave_count": 62,
        "tier": 7,
        "required_skills": [],
    },
    "E3": {
        "type": "NORMAL",
        "wave_count": 74,
        "tier": 9,
        "required_skills": [],
    },
    "E4": {
        "type": "EPIC",
        "wave_count": 74,
        "tier": 9,
        "required_skills": [],
    },
    "E5": {
        "type": "SECRET",
        "wave_count": 78,
        "tier": 10,
        "required_skills": [],
    },
    "F1": {
        "type": "NORMAL",
        "wave_count": 60,
        "tier": 7,
        "required_skills": [],
    },
    "F2": {
        "type": "NORMAL",
        "wave_count": 64,
        "tier": 7,
        "required_skills": [],
    },
    "F3": {
        "type": "NORMAL",
        "wave_count": 85,
        "tier": 11,
        "required_skills": [],
    },
    "F4": {
        "type": "NORMAL",
        "wave_count": 88,
        "tier": 11,
        "required_skills": [],
    },
    "F5": {
        "type": "SECRET",
        "wave_count": 90,
        "tier": 11,
        "required_skills": [],
    },
    "G1": {
        "type": "NORMAL",
        "wave_count": 50,
        "tier": 5,
        "required_skills": [],
    },
    "G2": {
        "type": "NORMAL",
        "wave_count": 52,
        "tier": 5,
        "required_skills": [],
    },
    "G3": {
        "type": "EPIC",
        "wave_count": 55,
        "tier": 6,
        "required_skills": [],
    },
    "G4": {
        "type": "TILE_GIVING",
        "wave_count": 56,
        "tier": 6,
        "required_skills": [],
    },
    "H1": {
        "type": "NORMAL",
        "wave_count": 64,
        "tier": 7,
        "required_skills": [],
    },
    "H2": {
        "type": "NORMAL",
        "wave_count": 66,
        "tier": 7,
        "required_skills": [],
    },
    "H3": {
        "type": "TILE_GIVING",
        "wave_count": 64,
        "tier": 7,
        "required_skills": [],
    },
    "H4": {
        "type": "NORMAL",
        "wave_count": 70,
        "tier": 8,
        "required_skills": [],
    },
    "H5": {
        "type": "SECRET",
        "wave_count": 68,
        "tier": 7,
        "required_skills": [],
    },
    "I1": {
        "type": "NORMAL",
        "wave_count": 76,
        "tier": 9,
        "required_skills": [],
    },
    "I2": {
        "type": "NORMAL",
        "wave_count": 78,
        "tier": 10,
        "required_skills": [],
    },
    "I3": {
        "type": "NORMAL",
        "wave_count": 80,
        "tier": 10,
        "required_skills": [],
    },
    "I4": {
        "type": "NORMAL",
        "wave_count": 82,
        "tier": 10,
        "required_skills": [],
    },
    "J1": {
        "type": "NORMAL",
        "wave_count": 55,
        "tier": 6,
        "required_skills": [],
    },
    "J2": {
        "type": "NORMAL",
        "wave_count": 54,
        "tier": 6,
        "required_skills": [],
    },
    "J3": {
        "type": "NORMAL",
        "wave_count": 56,
        "tier": 6,
        "required_skills": [],
    },
    "J4": {
        "type": "TILE_GIVING",
        "wave_count": 58,
        "tier": 6,
        "required_skills": [],
    },
    "K1": {
        "type": "STORY_RELATED",
        "wave_count": 46,
        "tier": 4,
        "required_skills": [],
    },
    "K2": {
        "type": "NORMAL",
        "wave_count": 46,
        "tier": 4,
        "required_skills": [],
    },
    "K3": {
        "type": "NORMAL",
        "wave_count": 50,
        "tier": 5,
        "required_skills": [],
    },
    "K4": {
        "type": "EPIC",
        "wave_count": 46,
        "tier": 4,
        "required_skills": [],
    },
    "K5": {
        "type": "SECRET",
        "wave_count": 54,
        "tier": 6,
        "required_skills": [],
    },
    "L1": {
        "type": "NORMAL",
        "wave_count": 44,
        "tier": 4,
        "required_skills": [],
    },
    "L2": {
        "type": "NORMAL",
        "wave_count": 46,
        "tier": 4,
        "required_skills": [],
    },
    "L3": {
        "type": "NORMAL",
        "wave_count": 46,
        "tier": 4,
        "required_skills": [],
    },
    "L4": {
        "type": "EPIC",
        "wave_count": 50,
        "tier": 5,
        "required_skills": [],
    },
    "L5": {
        "type": "EPIC",
        "wave_count": 64,
        "tier": 7,
        "required_skills": ["Freeze", "Bolt", "Beam", "Barrage"],
    },
    "M1": {
        "type": "NORMAL",
        "wave_count": 60,
        "tier": 7,
        "required_skills": [],
    },
    "M2": {
        "type": "NORMAL",
        "wave_count": 62,
        "tier": 7,
        "required_skills": [],
    },
    "M3": {
        "type": "NORMAL",
        "wave_count": 64,
        "tier": 7,
        "required_skills": [],
    },
    "M4": {
        "type": "NORMAL",
        "wave_count": 66,
        "tier": 7,
        "required_skills": [],
    },
    "N1": {
        "type": "NORMAL",
        "wave_count": 35,
        "tier": 3,
        "required_skills": [],
    },
    "N2": {
        "type": "NORMAL",
        "wave_count": 36,
        "tier": 3,
        "required_skills": [],
    },
    "N3": {
        "type": "NORMAL",
        "wave_count": 38,
        "tier": 3,
        "required_skills": [],
    },
    "N4": {
        "type": "NORMAL",
        "wave_count": 70,
        "tier": 8,
        "required_skills": [],
    },
    "N5": {
        "type": "NORMAL",
        "wave_count": 68,
        "tier": 7,
        "required_skills": [],
    },
    "O1": {
        "type": "NORMAL",
        "wave_count": 34,
        "tier": 3,
        "required_skills": [],
    },
    "O2": {
        "type": "NORMAL",
        "wave_count": 35,
        "tier": 3,
        "required_skills": [],
    },
    "O3": {
        "type": "NORMAL",
        "wave_count": 32,
        "tier": 2,
        "required_skills": [],
    },
    "O4": {
        "type": "EPIC",
        "wave_count": 33,
        "tier": 3,
        "required_skills": [],
    },
    "P1": {
        "type": "NORMAL",
        "wave_count": 38,
        "tier": 3,
        "required_skills": [],
    },
    "P2": {
        "type": "NORMAL",
        "wave_count": 42,
        "tier": 4,
        "required_skills": [],
    },
    "P3": {
        "type": "NORMAL",
        "wave_count": 40,
        "tier": 4,
        "required_skills": [],
    },
    "P4": {
        "type": "EPIC",
        "wave_count": 40,
        "tier": 4,
        "required_skills": [],
    },
    "P5": {
        "type": "NORMAL",
        "wave_count": 40,
        "tier": 4,
        "required_skills": ["Traps"],
    },
    "P6": {
        "type": "SECRET",
        "wave_count": 40,
        "tier": 4,
        "required_skills": [],
    },
    "Q1": {
        "type": "NORMAL",
        "wave_count": 24,
        "tier": 1,
        "required_skills": [],
    },
    "Q2": {
        "type": "NORMAL",
        "wave_count": 22,
        "tier": 1,
        "required_skills": [],
    },
    "Q3": {
        "type": "NORMAL",
        "wave_count": 24,
        "tier": 1,
        "required_skills": [],
    },
    "Q4": {
        "type": "EPIC",
        "wave_count": 26,
        "tier": 1,
        "required_skills": [],
    },
    "Q5": {
        "type": "NORMAL",
        "wave_count": 26,
        "tier": 1,
        "required_skills": [],
    },
    "R1": {
        "type": "NORMAL",
        "wave_count": 22,
        "tier": 1,
        "required_skills": [],
    },
    "R2": {
        "type": "EPIC",
        "wave_count": 22,
        "tier": 1,
        "required_skills": [],
    },
    "R3": {
        "type": "NORMAL",
        "wave_count": 30,
        "tier": 2,
        "required_skills": [],
    },
    "R4": {
        "type": "NORMAL",
        "wave_count": 30,
        "tier": 2,
        "required_skills": [],
    },
    "R5": {
        "type": "EPIC",
        "wave_count": 32,
        "tier": 2,
        "required_skills": [],
    },
    "R6": {
        "type": "SECRET",
        "wave_count": 36,
        "tier": 3,
        "required_skills": [],
    },
    "S1": {
        "type": "NORMAL",
        "wave_count": 14,
        "tier": 0,
        "required_skills": [],
    },
    "S2": {
        "type": "NORMAL",
        "wave_count": 16,
        "tier": 0,
        "required_skills": [],
    },
    "S3": {
        "type": "NORMAL",
        "wave_count": 14,
        "tier": 0,
        "required_skills": [],
    },
    "S4": {
        "type": "EPIC",
        "wave_count": 20,
        "tier": 0,
        "required_skills": [],
    },
    "T1": {
        "type": "NORMAL",
        "wave_count": 26,
        "tier": 1,
        "required_skills": [],
    },
    "T2": {
        "type": "STORY_RELATED",
        "wave_count": 28,
        "tier": 2,
        "required_skills": [],
    },
    "T3": {
        "type": "NORMAL",
        "wave_count": 28,
        "tier": 2,
        "required_skills": [],
    },
    "T4": {
        "type": "EPIC",
        "wave_count": 30,
        "tier": 2,
        "required_skills": [],
    },
    "T5": {
        "type": "SECRET",
        "wave_count": 40,
        "tier": 4,
        "required_skills": [],
    },
    "U1": {
        "type": "NORMAL",
        "wave_count": 30,
        "tier": 2,
        "required_skills": [],
    },
    "U2": {
        "type": "NORMAL",
        "wave_count": 32,
        "tier": 2,
        "required_skills": [],
    },
    "U3": {
        "type": "NORMAL",
        "wave_count": 30,
        "tier": 2,
        "required_skills": [],
    },
    "U4": {
        "type": "EPIC",
        "wave_count": 30,
        "tier": 2,
        "required_skills": [],
    },
    "V1": {
        "type": "NORMAL",
        "wave_count": 20,
        "tier": 0,
        "required_skills": [],
    },
    "V2": {
        "type": "NORMAL",
        "wave_count": 22,
        "tier": 1,
        "required_skills": [],
    },
    "V3": {
        "type": "NORMAL",
        "wave_count": 24,
        "tier": 1,
        "required_skills": [],
    },
    "V4": {
        "type": "EPIC",
        "wave_count": 24,
        "tier": 1,
        "required_skills": [],
    },
    "W1": {
        "type": "NORMAL",
        "wave_count": 6,
        "tier": 0,
        "required_skills": [],
    },
    "W2": {
        "type": "NORMAL",
        "wave_count": 8,
        "tier": 0,
        "required_skills": [],
    },
    "W3": {
        "type": "STORY_RELATED",
        "wave_count": 12,
        "tier": 0,
        "required_skills": [],
    },
    "W4": {
        "type": "EPIC",
        "wave_count": 14,
        "tier": 0,
        "required_skills": [],
    },
    "X1": {
        "type": "NORMAL",
        "wave_count": 42,
        "tier": 4,
        "required_skills": [],
    },
    "X2": {
        "type": "NORMAL",
        "wave_count": 48,
        "tier": 5,
        "required_skills": [],
    },
    "X3": {
        "type": "NORMAL",
        "wave_count": 44,
        "tier": 4,
        "required_skills": [],
    },
    "X4": {
        "type": "EPIC",
        "wave_count": 46,
        "tier": 4,
        "required_skills": [],
    },
    "Y1": {
        "type": "NORMAL",
        "wave_count": 32,
        "tier": 2,
        "required_skills": [],
    },
    "Y2": {
        "type": "NORMAL",
        "wave_count": 35,
        "tier": 3,
        "required_skills": [],
    },
    "Y3": {
        "type": "STORY_RELATED",
        "wave_count": 30,
        "tier": 2,
        "required_skills": [],
    },
    "Y4": {
        "type": "EPIC",
        "wave_count": 40,
        "tier": 4,
        "required_skills": [],
    },
    "Z1": {
        "type": "NORMAL",
        "wave_count": 44,
        "tier": 4,
        "required_skills": [],
    },
    "Z2": {
        "type": "NORMAL",
        "wave_count": 46,
        "tier": 4,
        "required_skills": [],
    },
    "Z3": {
        "type": "NORMAL",
        "wave_count": 46,
        "tier": 4,
        "required_skills": [],
    },
    "Z4": {
        "type": "NORMAL",
        "wave_count": 48,
        "tier": 5,
        "required_skills": [],
    },
    "Z5": {
        "type": "SECRET",
        "wave_count": 50,
        "tier": 5,
        "required_skills": [],
    },
}
