"""
GemCraft Frostborn Wrath — Level Progression Rules

Defines all 122 game stages and their unlock requirements.
Includes free stages (W1-W4) through endgame (A1-A6).
"""

# =====================================================================
# LEVEL REQUIREMENTS - All 122 stages
# =====================================================================
# Each stage entry can include:
#   - WaveCount, MonsterCount, ReaverWaves/Count/MaxHP/MaxArmor,
#     SwarmlingWaves/Count/MaxHP/MaxArmor, GiantWaves/Count/MaxHP/MaxArmor
#     — base monster stats. Zero-valued fields are omitted.
#   - <Type>Count fields (BeaconCount, MonsterNestCount, BarricadeCount,
#     ShrineCount, etc.) — only present when the stage actually has them.
#   - requirements: DNF list of Field_<sid> + counter gates needed to
#     unlock this stage.
#
level_requirements = {
    "A1": {
        "type": "NORMAL",
        "WaveCount": 90,
        "AvailableGems": ["CRITHIT", "BLEEDING", "ARMOR_TEARING", "POISON", "SLOWING"],
        "MonsterCount": 1436,
        "ReaverWaves": 30,
        "ReaverCount": 358,
        "ReaverMaxHP": 116260,
        "ReaverMaxArmor": 4623,
        "SwarmlingWaves": 30,
        "SwarmlingCount": 965,
        "SwarmlingMaxHP": 48457,
        "SwarmlingMaxArmor": 4947,
        "GiantWaves": 30,
        "GiantCount": 113,
        "GiantMaxHP": 1153349,
        "GiantMaxArmor": 4239,
        "MonstersBeforeWave12": 205,
        "MarkedMonsterCount": 57,
        "requirements": [
            ["Field_F4"],
            ["Field_C5"],
            ["Field_C4"],
        ],
    },
    "A2": {
        "type": "NORMAL",
        "WaveCount": 90,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING", "ARMOR_TEARING", "SLOWING"],
        "MonsterCount": 1533,
        "ReaverWaves": 30,
        "ReaverCount": 357,
        "ReaverMaxHP": 90448,
        "ReaverMaxArmor": 2249,
        "SwarmlingWaves": 30,
        "SwarmlingCount": 1061,
        "SwarmlingMaxHP": 43485,
        "SwarmlingMaxArmor": 2717,
        "GiantWaves": 30,
        "GiantCount": 115,
        "GiantMaxHP": 1397710,
        "GiantMaxArmor": 3083,
        "MonstersBeforeWave12": 193,
        "MarkedMonsterCount": 147,
        "requirements": [
            ["Field_F4"],
            ["Field_C5"],
            ["Field_C4"],
        ],
    },
    "A3": {
        "type": "NORMAL",
        "WaveCount": 90,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING", "ARMOR_TEARING", "POISON"],
        "MonsterCount": 1503,
        "ReaverWaves": 30,
        "ReaverCount": 380,
        "ReaverMaxHP": 102634,
        "ReaverMaxArmor": 2396,
        "SwarmlingWaves": 30,
        "SwarmlingCount": 1005,
        "SwarmlingMaxHP": 45901,
        "SwarmlingMaxArmor": 2717,
        "GiantWaves": 30,
        "GiantCount": 118,
        "GiantMaxHP": 1586008,
        "GiantMaxArmor": 3282,
        "MonstersBeforeWave12": 142,
        "MarkedMonsterCount": 123,
        "BeaconCount": 10,
        "requirements": [
            ["Field_A1"],
            ["Field_F5"],
            ["Field_A2"],
        ],
    },
    "A4": {
        "type": "NORMAL",
        "WaveCount": 100,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING", "ARMOR_TEARING", "POISON", "SLOWING"],
        "MonsterCount": 1570,
        "ReaverWaves": 40,
        "ReaverCount": 517,
        "ReaverMaxHP": 141663,
        "ReaverMaxArmor": 5698,
        "SwarmlingWaves": 30,
        "SwarmlingCount": 939,
        "SwarmlingMaxHP": 62768,
        "SwarmlingMaxArmor": 6402,
        "GiantWaves": 30,
        "GiantCount": 114,
        "GiantMaxHP": 2178948,
        "GiantMaxArmor": 7763,
        "MonstersBeforeWave12": 196,
        "MarkedMonsterCount": 242,
        "BeaconCount": 16,
        "GatekeeperCount": 1,
        "ObeliskCount": 2,
        "ShadowCount": 1,
        "WraithCount": 1,
        "requirements": [
            ["Field_A3"],
            ["Field_A6"],
            ["Field_A5"],
        ],
    },
    "A5": {
        "type": "NORMAL",
        "WaveCount": 96,
        "AvailableGems": ["ARMOR_TEARING", "POISON", "SLOWING"],
        "MonsterCount": 1617,
        "ReaverWaves": 36,
        "ReaverCount": 458,
        "ReaverMaxHP": 314395,
        "ReaverMaxArmor": 3965,
        "SwarmlingWaves": 30,
        "SwarmlingCount": 1058,
        "SwarmlingMaxHP": 112658,
        "SwarmlingMaxArmor": 3723,
        "GiantWaves": 30,
        "GiantCount": 101,
        "GiantMaxHP": 3075848,
        "GiantMaxArmor": 3722,
        "MonstersBeforeWave12": 126,
        "MarkedMonsterCount": 118,
        "requirements": [
            ["Field_F5"],
            ["Field_A1"],
            ["Field_A2"],
        ],
    },
    "A6": {
        "type": "NORMAL",
        "WaveCount": 99,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING"],
        "MonsterCount": 1642,
        "ReaverWaves": 33,
        "ReaverCount": 402,
        "ReaverMaxHP": 418679,
        "ReaverMaxArmor": 7579,
        "SwarmlingWaves": 33,
        "SwarmlingCount": 1120,
        "SwarmlingMaxHP": 150027,
        "SwarmlingMaxArmor": 7083,
        "GiantWaves": 33,
        "GiantCount": 120,
        "GiantMaxHP": 4777689,
        "GiantMaxArmor": 7952,
        "MonstersBeforeWave12": 228,
        "MarkedMonsterCount": 104,
        "requirements": [
            ["Field_A1"],
            ["Field_F5"],
            ["Field_A2"],
        ],
    },
    "B1": {
        "type": "NORMAL",
        "WaveCount": 76,
        "AvailableGems": ["CRITHIT", "BLEEDING", "SLOWING"],
        "MonsterCount": 1560,
        "ReaverWaves": 27,
        "ReaverCount": 351,
        "ReaverMaxHP": 21398,
        "ReaverMaxArmor": 626,
        "SwarmlingWaves": 33,
        "SwarmlingCount": 1146,
        "SwarmlingMaxHP": 11059,
        "SwarmlingMaxArmor": 791,
        "GiantWaves": 16,
        "GiantCount": 63,
        "GiantMaxHP": 382131,
        "GiantMaxArmor": 964,
        "MonstersBeforeWave12": 188,
        "MarkedMonsterCount": 91,
        "BarricadeCount": 24,
        "MonsterNestCount": 1,
        "TombCount": 1,
        "requirements": [
            ["Field_E4"],
            ["Field_E3"],
            ["Field_D2"],
        ],
    },
    "B2": {
        "type": "NORMAL",
        "WaveCount": 80,
        "AvailableGems": ["MANA_LEECHING", "BLEEDING", "ARMOR_TEARING", "POISON", "SLOWING"],
        "MonsterCount": 2509,
        "ReaverWaves": 6,
        "ReaverCount": 79,
        "ReaverMaxHP": 10277,
        "ReaverMaxArmor": 388,
        "SwarmlingWaves": 70,
        "SwarmlingCount": 2414,
        "SwarmlingMaxHP": 5021,
        "SwarmlingMaxArmor": 472,
        "GiantWaves": 4,
        "GiantCount": 16,
        "GiantMaxHP": 104147,
        "GiantMaxArmor": 378,
        "MonstersBeforeWave12": 349,
        "MarkedMonsterCount": 39,
        "MonsterNestCount": 1,
        "requirements": [
            ["Field_I1"],
            ["Field_D3"],
            ["Field_B1"],
        ],
    },
    "B3": {
        "type": "NORMAL",
        "WaveCount": 86,
        "AvailableGems": ["BLEEDING", "ARMOR_TEARING", "SLOWING"],
        "MonsterCount": 2414,
        "ReaverWaves": 12,
        "ReaverCount": 154,
        "ReaverMaxHP": 34915,
        "ReaverMaxArmor": 1189,
        "SwarmlingWaves": 66,
        "SwarmlingCount": 2232,
        "SwarmlingMaxHP": 16553,
        "SwarmlingMaxArmor": 1416,
        "GiantWaves": 8,
        "GiantCount": 28,
        "GiantMaxHP": 574626,
        "GiantMaxArmor": 1721,
        "MonstersBeforeWave12": 356,
        "MarkedMonsterCount": 180,
        "BarricadeCount": 10,
        "requirements": [
            ["Field_C1"],
            ["Field_I4"],
            ["Field_B5"],
        ],
    },
    "B4": {
        "type": "NORMAL",
        "WaveCount": 80,
        "AvailableGems": ["MANA_LEECHING", "ARMOR_TEARING", "POISON"],
        "MonsterCount": 1766,
        "ReaverWaves": 27,
        "ReaverCount": 319,
        "ReaverMaxHP": 25992,
        "ReaverMaxArmor": 888,
        "SwarmlingWaves": 41,
        "SwarmlingCount": 1405,
        "SwarmlingMaxHP": 11516,
        "SwarmlingMaxArmor": 998,
        "GiantWaves": 12,
        "GiantCount": 42,
        "GiantMaxHP": 304994,
        "GiantMaxArmor": 964,
        "MonstersBeforeWave12": 243,
        "MarkedMonsterCount": 38,
        "BarricadeCount": 10,
        "ShrineCount": 1,
        "SleepingHiveCount": 2,
        "requirements": [
            ["Field_I2"],
            ["Field_D5"],
            ["Field_E5"],
            ["Field_B2"],
        ],
    },
    "B5": {
        "type": "SECRET",
        "WaveCount": 84,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING", "ARMOR_TEARING", "POISON", "SLOWING"],
        "MonsterCount": 2109,
        "ReaverWaves": 18,
        "ReaverCount": 234,
        "ReaverMaxHP": 23430,
        "ReaverMaxArmor": 807,
        "SwarmlingWaves": 56,
        "SwarmlingCount": 1843,
        "SwarmlingMaxHP": 9657,
        "SwarmlingMaxArmor": 851,
        "GiantWaves": 10,
        "GiantCount": 32,
        "GiantMaxHP": 278832,
        "GiantMaxArmor": 888,
        "MonstersBeforeWave12": 209,
        "MarkedMonsterCount": 217,
        "MonsterNestCount": 3,
        "requirements": [
            ["Field_I3"],
            ["Field_C2"],
            ["Field_B4"],
        ],
    },
    "C1": {
        "type": "NORMAL",
        "WaveCount": 82,
        "AvailableGems": ["MANA_LEECHING", "BLEEDING", "POISON"],
        "MonsterCount": 1370,
        "ReaverWaves": 28,
        "ReaverCount": 350,
        "ReaverMaxHP": 13653,
        "ReaverMaxArmor": 450,
        "SwarmlingWaves": 27,
        "SwarmlingCount": 926,
        "SwarmlingMaxHP": 6293,
        "SwarmlingMaxArmor": 520,
        "GiantWaves": 27,
        "GiantCount": 94,
        "GiantMaxHP": 208035,
        "GiantMaxArmor": 612,
        "MonstersBeforeWave12": 205,
        "MarkedMonsterCount": 58,
        "BarricadeCount": 3,
        "BeaconCount": 8,
        "MonsterNestCount": 1,
        "SealedGemCount": 1,
        "requirements": [
            ["Field_C2"],
            ["Field_I3"],
            ["Field_B4"],
        ],
    },
    "C2": {
        "type": "NORMAL",
        "WaveCount": 80,
        "AvailableGems": ["CRITHIT", "ARMOR_TEARING", "SLOWING"],
        "MonsterCount": 1346,
        "ReaverWaves": 28,
        "ReaverCount": 350,
        "ReaverMaxHP": 29339,
        "ReaverMaxArmor": 998,
        "SwarmlingWaves": 26,
        "SwarmlingCount": 901,
        "SwarmlingMaxHP": 10612,
        "SwarmlingMaxArmor": 942,
        "GiantWaves": 26,
        "GiantCount": 95,
        "GiantMaxHP": 344267,
        "GiantMaxArmor": 1082,
        "MonstersBeforeWave12": 179,
        "MarkedMonsterCount": 94,
        "CorruptedManaShardCount": 1,
        "ManaShardCount": 4,
        "requirements": [
            ["Field_E5"],
            ["Field_B2"],
            ["Field_I2"],
        ],
    },
    "C3": {
        "type": "NORMAL",
        "WaveCount": 84,
        "AvailableGems": ["CRITHIT", "POISON", "SLOWING"],
        "MonsterCount": 1452,
        "ReaverWaves": 28,
        "ReaverCount": 349,
        "ReaverMaxHP": 27560,
        "ReaverMaxArmor": 851,
        "SwarmlingWaves": 28,
        "SwarmlingCount": 998,
        "SwarmlingMaxHP": 8291,
        "SwarmlingMaxArmor": 687,
        "GiantWaves": 28,
        "GiantCount": 105,
        "GiantMaxHP": 371996,
        "GiantMaxArmor": 1042,
        "MonstersBeforeWave12": 179,
        "MarkedMonsterCount": 147,
        "BarricadeCount": 27,
        "MonsterNestCount": 2,
        "requirements": [
            ["Field_I4"],
            ["Field_B5"],
            ["Field_C1"],
        ],
    },
    "C4": {
        "type": "TILE_GIVING",
        "WaveCount": 87,
        "AvailableGems": ["MANA_LEECHING", "BLEEDING", "ARMOR_TEARING"],
        "MonsterCount": 1427,
        "ReaverWaves": 29,
        "ReaverCount": 355,
        "ReaverMaxHP": 32527,
        "ReaverMaxArmor": 947,
        "SwarmlingWaves": 29,
        "SwarmlingCount": 964,
        "SwarmlingMaxHP": 10421,
        "SwarmlingMaxArmor": 807,
        "GiantWaves": 29,
        "GiantCount": 108,
        "GiantMaxHP": 497964,
        "GiantMaxArmor": 1289,
        "MonstersBeforeWave12": 161,
        "MarkedMonsterCount": 196,
        "BeaconCount": 6,
        "ObeliskCount": 1,
        "requirements": [
            ["Field_C3"],
            ["Field_B3"],
            ["Field_F3"],
        ],
    },
    "C5": {
        "type": "EPIC",
        "WaveCount": 90,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING", "ARMOR_TEARING"],
        "LanternCount": 4,
        "MonsterCount": 1524,
        "ReaverWaves": 30,
        "ReaverCount": 367,
        "ReaverMaxHP": 43475,
        "ReaverMaxArmor": 1787,
        "SwarmlingWaves": 30,
        "SwarmlingCount": 1042,
        "SwarmlingMaxHP": 12280,
        "SwarmlingMaxArmor": 1336,
        "GiantWaves": 30,
        "GiantCount": 115,
        "GiantMaxHP": 586802,
        "GiantMaxArmor": 2171,
        "MonstersBeforeWave12": 232,
        "MarkedMonsterCount": 156,
        "ShadowCount": 1,
        "requirements": [
            ["Field_F3"],
            ["Field_B3"],
            ["Field_C3"],
        ],
    },
    "D1": {
        "type": "NORMAL",
        "WaveCount": 72,
        "AvailableGems": ["MANA_LEECHING", "POISON", "SLOWING"],
        "MonsterCount": 1066,
        "ReaverWaves": 23,
        "ReaverCount": 251,
        "ReaverMaxHP": 6309,
        "ReaverMaxArmor": 331,
        "SwarmlingWaves": 22,
        "SwarmlingCount": 712,
        "SwarmlingMaxHP": 2908,
        "SwarmlingMaxArmor": 383,
        "GiantWaves": 27,
        "GiantCount": 103,
        "GiantMaxHP": 101904,
        "GiantMaxArmor": 474,
        "MonstersBeforeWave12": 190,
        "MarkedMonsterCount": 35,
        "BarricadeCount": 6,
        "requirements": [
            ["Field_N5"],
            ["Field_E1"],
            ["Field_N4"],
        ],
    },
    "D2": {
        "type": "NORMAL",
        "WaveCount": 75,
        "AvailableGems": ["CRITHIT", "BLEEDING", "SLOWING"],
        "MonsterCount": 1128,
        "ReaverWaves": 28,
        "ReaverCount": 357,
        "ReaverMaxHP": 13206,
        "ReaverMaxArmor": 631,
        "SwarmlingWaves": 21,
        "SwarmlingCount": 676,
        "SwarmlingMaxHP": 3503,
        "SwarmlingMaxArmor": 457,
        "GiantWaves": 26,
        "GiantCount": 95,
        "GiantMaxHP": 167368,
        "GiantMaxArmor": 734,
        "MonstersBeforeWave12": 134,
        "MarkedMonsterCount": 52,
        "MonsterNestCount": 4,
        "requirements": [
            ["Field_H4"],
            ["Field_D4"],
            ["Field_D1"],
        ],
    },
    "D3": {
        "type": "EPIC",
        "WaveCount": 77,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING", "ARMOR_TEARING"],
        "MonsterCount": 1134,
        "ReaverWaves": 32,
        "ReaverCount": 390,
        "ReaverMaxHP": 9147,
        "ReaverMaxArmor": 423,
        "SwarmlingWaves": 20,
        "SwarmlingCount": 647,
        "SwarmlingMaxHP": 3977,
        "SwarmlingMaxArmor": 466,
        "GiantWaves": 25,
        "GiantCount": 97,
        "GiantMaxHP": 156601,
        "GiantMaxArmor": 633,
        "MonstersBeforeWave12": 148,
        "requirements": [
            ["Field_E3"],
            ["Field_E4"],
            ["Field_D2"],
        ],
    },
    "D4": {
        "type": "NORMAL",
        "WaveCount": 70,
        "AvailableGems": ["CRITHIT", "BLEEDING", "POISON"],
        "MonsterCount": 1078,
        "ReaverWaves": 21,
        "ReaverCount": 251,
        "ReaverMaxHP": 14488,
        "ReaverMaxArmor": 669,
        "SwarmlingWaves": 21,
        "SwarmlingCount": 719,
        "SwarmlingMaxHP": 5240,
        "SwarmlingMaxArmor": 631,
        "GiantWaves": 28,
        "GiantCount": 108,
        "GiantMaxHP": 170013,
        "GiantMaxArmor": 727,
        "MonstersBeforeWave12": 160,
        "MarkedMonsterCount": 5,
        "MonsterNestCount": 1,
        "requirements": [
            ["Field_N4"],
            ["Field_N5"],
            ["Field_E1"],
        ],
    },
    "D5": {
        "type": "NORMAL",
        "WaveCount": 78,
        "AvailableGems": ["MANA_LEECHING", "ARMOR_TEARING", "SLOWING"],
        "MonsterCount": 1097,
        "ReaverWaves": 23,
        "ReaverCount": 273,
        "ReaverMaxHP": 13027,
        "ReaverMaxArmor": 496,
        "SwarmlingWaves": 21,
        "SwarmlingCount": 727,
        "SwarmlingMaxHP": 5394,
        "SwarmlingMaxArmor": 526,
        "GiantWaves": 28,
        "GiantCount": 97,
        "GiantMaxHP": 245468,
        "GiantMaxArmor": 809,
        "MonstersBeforeWave12": 109,
        "MarkedMonsterCount": 24,
        "requirements": [
            ["Field_D3"],
            ["Field_I1"],
            ["Field_B1"],
        ],
    },
    "E1": {
        "type": "NORMAL",
        "WaveCount": 70,
        "AvailableGems": ["CRITHIT", "POISON", "SLOWING"],
        "LanternCount": 4,
        "PylonCount": 2,
        "MonsterCount": 1228,
        "ReaverWaves": 32,
        "ReaverCount": 399,
        "ReaverMaxHP": 7530,
        "ReaverMaxArmor": 526,
        "SwarmlingWaves": 22,
        "SwarmlingCount": 769,
        "SwarmlingMaxHP": 2413,
        "SwarmlingMaxArmor": 441,
        "GiantWaves": 16,
        "GiantCount": 60,
        "GiantMaxHP": 115288,
        "GiantMaxArmor": 721,
        "MonstersBeforeWave12": 136,
        "MarkedMonsterCount": 49,
        "BarricadeCount": 10,
        "requirements": [
            ["Field_H5"],
            ["Field_M4"],
            ["Field_H2"],
        ],
    },
    "E2": {
        "type": "NORMAL",
        "WaveCount": 62,
        "AvailableGems": ["MANA_LEECHING", "ARMOR_TEARING", "POISON"],
        "MonsterCount": 1084,
        "ReaverWaves": 24,
        "ReaverCount": 303,
        "ReaverMaxHP": 4725,
        "ReaverMaxArmor": 330,
        "SwarmlingWaves": 22,
        "SwarmlingCount": 720,
        "SwarmlingMaxHP": 1947,
        "SwarmlingMaxArmor": 350,
        "GiantWaves": 16,
        "GiantCount": 61,
        "GiantMaxHP": 63782,
        "GiantMaxArmor": 405,
        "MonstersBeforeWave12": 189,
        "MonsterNestCount": 1,
        "SpireCount": 1,
        "requirements": [
            ["Field_M1"],
            ["Field_J4"],
            ["Field_F1"],
        ],
    },
    "E3": {
        "type": "NORMAL",
        "WaveCount": 74,
        "AvailableGems": ["MANA_LEECHING", "BLEEDING", "SLOWING"],
        "MonsterCount": 1337,
        "ReaverWaves": 32,
        "ReaverCount": 390,
        "ReaverMaxHP": 7880,
        "ReaverMaxArmor": 249,
        "SwarmlingWaves": 26,
        "SwarmlingCount": 889,
        "SwarmlingMaxHP": 2561,
        "SwarmlingMaxArmor": 218,
        "GiantWaves": 16,
        "GiantCount": 58,
        "GiantMaxHP": 89729,
        "GiantMaxArmor": 273,
        "MonstersBeforeWave12": 142,
        "MarkedMonsterCount": 77,
        "BarricadeCount": 1,
        "MonsterNestCount": 3,
        "requirements": [
            ["Field_D4"],
            ["Field_D1"],
            ["Field_H4"],
        ],
    },
    "E4": {
        "type": "EPIC",
        "WaveCount": 74,
        "AvailableGems": ["BLEEDING", "ARMOR_TEARING", "POISON", "SLOWING"],
        "MonsterCount": 1061,
        "ReaverWaves": 41,
        "ReaverCount": 500,
        "ReaverMaxHP": 11507,
        "ReaverMaxArmor": 704,
        "SwarmlingWaves": 15,
        "SwarmlingCount": 494,
        "SwarmlingMaxHP": 2527,
        "SwarmlingMaxArmor": 416,
        "GiantWaves": 18,
        "GiantCount": 67,
        "GiantMaxHP": 155322,
        "GiantMaxArmor": 858,
        "MonstersBeforeWave12": 142,
        "MarkedMonsterCount": 22,
        "CorruptedManaShardCount": 1,
        "ManaShardCount": 9,
        "ShadowCount": 1,
        "SpecterCount": 1,
        "requirements": [
            ["Field_D4"],
            ["Field_H4"],
            ["Field_D1"],
        ],
    },
    "E5": {
        "type": "SECRET",
        "WaveCount": 78,
        "AvailableGems": ["CRITHIT", "POISON"],
        "MonsterCount": 1391,
        "ReaverWaves": 34,
        "ReaverCount": 388,
        "ReaverMaxHP": 17930,
        "ReaverMaxArmor": 895,
        "SwarmlingWaves": 26,
        "SwarmlingCount": 937,
        "SwarmlingMaxHP": 8500,
        "SwarmlingMaxArmor": 1066,
        "GiantWaves": 18,
        "GiantCount": 66,
        "GiantMaxHP": 295090,
        "GiantMaxArmor": 1298,
        "MonstersBeforeWave12": 208,
        "MarkedMonsterCount": 15,
        "BarricadeCount": 6,
        "TombCount": 4,
        "requirements": [
            ["Field_D3"],
            ["Field_I1"],
            ["Field_B1"],
        ],
    },
    "F1": {
        "type": "NORMAL",
        "WaveCount": 60,
        "AvailableGems": ["MANA_LEECHING", "POISON", "SLOWING"],
        "TowerCount": 3,
        "OldWallCount": 22,
        "MonsterCount": 812,
        "ReaverWaves": 16,
        "ReaverCount": 211,
        "ReaverMaxHP": 5439,
        "ReaverMaxArmor": 463,
        "SwarmlingWaves": 14,
        "SwarmlingCount": 482,
        "SwarmlingMaxHP": 1821,
        "SwarmlingMaxArmor": 408,
        "GiantWaves": 30,
        "GiantCount": 119,
        "GiantMaxHP": 84051,
        "GiantMaxArmor": 639,
        "MonstersBeforeWave12": 114,
        "MarkedMonsterCount": 4,
        "AbandonedDwellingCount": 13,
        "DropHolderCount": 19,
        "requirements": [
            ["Field_G3"],
            ["Field_J3"],
            ["Field_G4"],
        ],
    },
    "F2": {
        "type": "NORMAL",
        "WaveCount": 64,
        "AvailableGems": ["CRITHIT", "BLEEDING", "ARMOR_TEARING"],
        "MonsterCount": 706,
        "ReaverWaves": 16,
        "ReaverCount": 194,
        "ReaverMaxHP": 7999,
        "ReaverMaxArmor": 634,
        "SwarmlingWaves": 14,
        "SwarmlingCount": 385,
        "SwarmlingMaxHP": 2492,
        "SwarmlingMaxArmor": 525,
        "GiantWaves": 34,
        "GiantCount": 127,
        "GiantMaxHP": 106964,
        "GiantMaxArmor": 770,
        "MonstersBeforeWave12": 143,
        "MarkedMonsterCount": 16,
        "RainCount": 1,
        "requirements": [
            ["Field_E2"],
            ["Field_M2"],
            ["Field_M3"],
        ],
    },
    "F3": {
        "type": "NORMAL",
        "WaveCount": 85,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING"],
        "MonsterCount": 1131,
        "ReaverWaves": 22,
        "ReaverCount": 265,
        "ReaverMaxHP": 41205,
        "ReaverMaxArmor": 1260,
        "SwarmlingWaves": 20,
        "SwarmlingCount": 706,
        "SwarmlingMaxHP": 17062,
        "SwarmlingMaxArmor": 1336,
        "GiantWaves": 43,
        "GiantCount": 160,
        "GiantMaxHP": 483503,
        "GiantMaxArmor": 1364,
        "MonstersBeforeWave12": 109,
        "MarkedMonsterCount": 36,
        "BarricadeCount": 6,
        "RainCount": 1,
        "TombCount": 1,
        "requirements": [
            ["Field_B5"],
            ["Field_I4"],
            ["Field_C1"],
        ],
    },
    "F4": {
        "type": "NORMAL",
        "WaveCount": 88,
        "AvailableGems": ["CRITHIT", "BLEEDING", "SLOWING"],
        "MonsterCount": 978,
        "ReaverWaves": 16,
        "ReaverCount": 196,
        "ReaverMaxHP": 55811,
        "ReaverMaxArmor": 1591,
        "SwarmlingWaves": 17,
        "SwarmlingCount": 578,
        "SwarmlingMaxHP": 20186,
        "SwarmlingMaxArmor": 1501,
        "GiantWaves": 55,
        "GiantCount": 204,
        "GiantMaxHP": 654896,
        "GiantMaxArmor": 1721,
        "MonstersBeforeWave12": 121,
        "MarkedMonsterCount": 5,
        "BarricadeCount": 14,
        "RainCount": 1,
        "requirements": [
            ["Field_F3"],
            ["Field_C3"],
            ["Field_B3"],
        ],
    },
    "F5": {
        "type": "SECRET",
        "WaveCount": 90,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING", "ARMOR_TEARING", "POISON", "SLOWING"],
        "OldWallCount": 50,
        "MonsterCount": 716,
        "ReaverWaves": 8,
        "ReaverCount": 98,
        "ReaverMaxHP": 57611,
        "ReaverMaxArmor": 1591,
        "SwarmlingWaves": 12,
        "SwarmlingCount": 364,
        "SwarmlingMaxHP": 14857,
        "SwarmlingMaxArmor": 1121,
        "GiantWaves": 70,
        "GiantCount": 254,
        "GiantMaxHP": 948161,
        "GiantMaxArmor": 2301,
        "MonstersBeforeWave12": 95,
        "MarkedMonsterCount": 15,
        "BarricadeCount": 12,
        "RainCount": 1,
        "requirements": [
            ["Field_C4"],
            ["Field_C5"],
            ["Field_F4"],
        ],
    },
    "G1": {
        "type": "NORMAL",
        "WaveCount": 50,
        "AvailableGems": ["CRITHIT", "BLEEDING", "POISON"],
        "PylonCount": 4,
        "MonsterCount": 628,
        "ReaverWaves": 22,
        "ReaverCount": 265,
        "ReaverMaxHP": 2595,
        "ReaverMaxArmor": 263,
        "SwarmlingWaves": 10,
        "SwarmlingCount": 308,
        "SwarmlingMaxHP": 752,
        "SwarmlingMaxArmor": 204,
        "GiantWaves": 18,
        "GiantCount": 55,
        "GiantMaxHP": 34701,
        "GiantMaxArmor": 323,
        "MonstersBeforeWave12": 219,
        "MarkedMonsterCount": 48,
        "requirements": [
            ["Field_L4"],
            ["Field_X2"],
            ["Field_Z4"],
            ["Field_K5"],
        ],
    },
    "G2": {
        "type": "NORMAL",
        "WaveCount": 52,
        "AvailableGems": ["MANA_LEECHING", "POISON", "SLOWING"],
        "MonsterCount": 608,
        "ReaverWaves": 20,
        "ReaverCount": 267,
        "ReaverMaxHP": 1484,
        "ReaverMaxArmor": 144,
        "SwarmlingWaves": 8,
        "SwarmlingCount": 246,
        "SwarmlingMaxHP": 190,
        "SwarmlingMaxArmor": 57,
        "GiantWaves": 24,
        "GiantCount": 95,
        "GiantMaxHP": 20125,
        "GiantMaxArmor": 183,
        "MonstersBeforeWave12": 133,
        "MarkedMonsterCount": 24,
        "MonsterNestCount": 3,
        "requirements": [
            ["Field_X2"],
            ["Field_Z4"],
            ["Field_K5"],
            ["Field_L4"],
        ],
    },
    "G3": {
        "type": "EPIC",
        "WaveCount": 55,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING", "ARMOR_TEARING"],
        "OldWallCount": 30,
        "MonsterCount": 638,
        "ReaverWaves": 20,
        "ReaverCount": 243,
        "ReaverMaxHP": 2115,
        "ReaverMaxArmor": 162,
        "SwarmlingWaves": 10,
        "SwarmlingCount": 301,
        "SwarmlingMaxHP": 722,
        "SwarmlingMaxArmor": 145,
        "GiantWaves": 25,
        "GiantCount": 94,
        "GiantMaxHP": 34486,
        "GiantMaxArmor": 237,
        "MonstersBeforeWave12": 180,
        "MarkedMonsterCount": 2,
        "ShadowCount": 1,
        "requirements": [
            ["Field_J1"],
            ["Field_J2"],
            ["Field_Z5"],
        ],
    },
    "G4": {
        "type": "TILE_GIVING",
        "WaveCount": 56,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING"],
        "AmplifierCount": 4,
        "TowerCount": 7,
        "WallCount": 9,
        "OldWallCount": 104,
        "MonsterCount": 827,
        "ReaverWaves": 26,
        "ReaverCount": 350,
        "ReaverMaxHP": 3874,
        "ReaverMaxArmor": 300,
        "SwarmlingWaves": 12,
        "SwarmlingCount": 418,
        "SwarmlingMaxHP": 629,
        "SwarmlingMaxArmor": 141,
        "GiantWaves": 18,
        "GiantCount": 59,
        "GiantMaxHP": 59858,
        "GiantMaxArmor": 415,
        "MonstersBeforeWave12": 146,
        "requirements": [
            ["Field_J1"],
            ["Field_J2"],
            ["Field_Z5"],
        ],
    },
    "H1": {
        "type": "NORMAL",
        "WaveCount": 64,
        "AvailableGems": ["CRITHIT", "BLEEDING", "ARMOR_TEARING"],
        "MonsterCount": 1051,
        "ReaverWaves": 20,
        "ReaverCount": 252,
        "ReaverMaxHP": 9522,
        "ReaverMaxArmor": 528,
        "SwarmlingWaves": 22,
        "SwarmlingCount": 730,
        "SwarmlingMaxHP": 1922,
        "SwarmlingMaxArmor": 300,
        "GiantWaves": 22,
        "GiantCount": 69,
        "GiantMaxHP": 127334,
        "GiantMaxArmor": 642,
        "MonstersBeforeWave12": 168,
        "MarkedMonsterCount": 141,
        "MonsterNestCount": 1,
        "requirements": [
            ["Field_E2"],
            ["Field_M3"],
            ["Field_M2"],
        ],
    },
    "H2": {
        "type": "NORMAL",
        "WaveCount": 66,
        "AvailableGems": ["MANA_LEECHING", "BLEEDING", "POISON"],
        "MonsterCount": 1048,
        "ReaverWaves": 26,
        "ReaverCount": 305,
        "ReaverMaxHP": 6531,
        "ReaverMaxArmor": 393,
        "SwarmlingWaves": 20,
        "SwarmlingCount": 668,
        "SwarmlingMaxHP": 2362,
        "SwarmlingMaxArmor": 371,
        "GiantWaves": 20,
        "GiantCount": 75,
        "GiantMaxHP": 107482,
        "GiantMaxArmor": 572,
        "MonstersBeforeWave12": 139,
        "MarkedMonsterCount": 52,
        "BeaconCount": 3,
        "ShrineCount": 2,
        "requirements": [
            ["Field_L5"],
            ["Field_F2"],
            ["Field_H1"],
        ],
    },
    "H3": {
        "type": "TILE_GIVING",
        "WaveCount": 64,
        "AvailableGems": ["ARMOR_TEARING", "SLOWING"],
        "MonsterCount": 1024,
        "ReaverWaves": 24,
        "ReaverCount": 288,
        "ReaverMaxHP": 6815,
        "ReaverMaxArmor": 393,
        "SwarmlingWaves": 20,
        "SwarmlingCount": 659,
        "SwarmlingMaxHP": 2012,
        "SwarmlingMaxArmor": 311,
        "GiantWaves": 20,
        "GiantCount": 77,
        "GiantMaxHP": 91554,
        "GiantMaxArmor": 482,
        "MonstersBeforeWave12": 135,
        "MarkedMonsterCount": 85,
        "BarricadeCount": 23,
        "requirements": [
            ["Field_E2"],
            ["Field_M3"],
            ["Field_M2"],
        ],
    },
    "H4": {
        "type": "NORMAL",
        "WaveCount": 70,
        "AvailableGems": ["CRITHIT", "ARMOR_TEARING", "POISON", "SLOWING"],
        "MonsterCount": 1087,
        "ReaverWaves": 26,
        "ReaverCount": 308,
        "ReaverMaxHP": 8127,
        "ReaverMaxArmor": 599,
        "SwarmlingWaves": 22,
        "SwarmlingCount": 701,
        "SwarmlingMaxHP": 4123,
        "SwarmlingMaxArmor": 771,
        "GiantWaves": 22,
        "GiantCount": 78,
        "GiantMaxHP": 143118,
        "GiantMaxArmor": 935,
        "MonstersBeforeWave12": 199,
        "MarkedMonsterCount": 86,
        "requirements": [
            ["Field_N4"],
            ["Field_N5"],
            ["Field_E1"],
        ],
    },
    "H5": {
        "type": "SECRET",
        "WaveCount": 68,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING", "ARMOR_TEARING", "POISON", "SLOWING"],
        "MonsterCount": 1104,
        "ReaverWaves": 25,
        "ReaverCount": 320,
        "ReaverMaxHP": 8522,
        "ReaverMaxArmor": 468,
        "SwarmlingWaves": 21,
        "SwarmlingCount": 710,
        "SwarmlingMaxHP": 3529,
        "SwarmlingMaxArmor": 496,
        "GiantWaves": 22,
        "GiantCount": 74,
        "GiantMaxHP": 107008,
        "GiantMaxArmor": 540,
        "MonstersBeforeWave12": 147,
        "MarkedMonsterCount": 74,
        "BarricadeCount": 23,
        "requirements": [
            ["Field_H1"],
            ["Field_L5"],
            ["Field_F2"],
            ["Field_H3"],
        ],
    },
    "I1": {
        "type": "NORMAL",
        "WaveCount": 76,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING"],
        "TowerCount": 1,
        "MonsterCount": 898,
        "ReaverWaves": 35,
        "ReaverCount": 441,
        "ReaverMaxHP": 18677,
        "ReaverMaxArmor": 895,
        "SwarmlingWaves": 10,
        "SwarmlingCount": 340,
        "SwarmlingMaxHP": 6755,
        "SwarmlingMaxArmor": 844,
        "GiantWaves": 30,
        "GiantCount": 117,
        "GiantMaxHP": 234499,
        "GiantMaxArmor": 1029,
        "MonstersBeforeWave12": 140,
        "MarkedMonsterCount": 51,
        "BarricadeCount": 5,
        "requirements": [
            ["Field_E4"],
            ["Field_E3"],
            ["Field_D2"],
        ],
    },
    "I2": {
        "type": "NORMAL",
        "WaveCount": 78,
        "AvailableGems": ["BLEEDING", "POISON", "SLOWING"],
        "MonsterCount": 735,
        "ReaverWaves": 24,
        "ReaverCount": 308,
        "ReaverMaxHP": 18153,
        "ReaverMaxArmor": 704,
        "SwarmlingWaves": 8,
        "SwarmlingCount": 260,
        "SwarmlingMaxHP": 4089,
        "SwarmlingMaxArmor": 441,
        "GiantWaves": 46,
        "GiantCount": 167,
        "GiantMaxHP": 342053,
        "GiantMaxArmor": 1146,
        "MonstersBeforeWave12": 164,
        "MarkedMonsterCount": 15,
        "AbandonedDwellingCount": 4,
        "DropHolderCount": 7,
        "TombCount": 1,
        "requirements": [
            ["Field_I1"],
            ["Field_B1"],
            ["Field_D3"],
        ],
    },
    "I3": {
        "type": "NORMAL",
        "WaveCount": 80,
        "AvailableGems": ["BLEEDING", "ARMOR_TEARING", "POISON"],
        "MonsterCount": 509,
        "ReaverWaves": 9,
        "ReaverCount": 117,
        "ReaverMaxHP": 28291,
        "ReaverMaxArmor": 1198,
        "SwarmlingWaves": 5,
        "SwarmlingCount": 169,
        "SwarmlingMaxHP": 3466,
        "SwarmlingMaxArmor": 445,
        "GiantWaves": 66,
        "GiantCount": 223,
        "GiantMaxHP": 380075,
        "GiantMaxArmor": 1457,
        "MonstersBeforeWave12": 74,
        "MarkedMonsterCount": 8,
        "BarricadeCount": 32,
        "requirements": [
            ["Field_D5"],
            ["Field_E5"],
            ["Field_B2"],
        ],
    },
    "I4": {
        "type": "NORMAL",
        "WaveCount": 82,
        "AvailableGems": ["BLEEDING"],
        "MonsterCount": 298,
        "GiantWaves": 82,
        "GiantCount": 298,
        "GiantMaxHP": 482856,
        "GiantMaxArmor": 1445,
        "MonstersBeforeWave12": 42,
        "MarkedMonsterCount": 27,
        "BarricadeCount": 12,
        "RainCount": 1,
        "requirements": [
            ["Field_C2"],
            ["Field_B4"],
            ["Field_I3"],
        ],
    },
    "J1": {
        "type": "NORMAL",
        "WaveCount": 55,
        "AvailableGems": ["MANA_LEECHING", "ARMOR_TEARING", "SLOWING"],
        "MonsterCount": 990,
        "ReaverWaves": 24,
        "ReaverCount": 279,
        "ReaverMaxHP": 2062,
        "ReaverMaxArmor": 152,
        "SwarmlingWaves": 20,
        "SwarmlingCount": 674,
        "SwarmlingMaxHP": 582,
        "SwarmlingMaxArmor": 119,
        "GiantWaves": 11,
        "GiantCount": 37,
        "GiantMaxHP": 33623,
        "GiantMaxArmor": 220,
        "MonstersBeforeWave12": 175,
        "MonsterNestCount": 3,
        "RainCount": 1,
        "requirements": [
            ["Field_K3"],
            ["Field_G2"],
            ["Field_G1"],
        ],
    },
    "J2": {
        "type": "NORMAL",
        "WaveCount": 54,
        "AvailableGems": ["CRITHIT", "POISON"],
        "LanternCount": 4,
        "MonsterCount": 1194,
        "ReaverWaves": 19,
        "ReaverCount": 243,
        "ReaverMaxHP": 4431,
        "ReaverMaxArmor": 433,
        "SwarmlingWaves": 26,
        "SwarmlingCount": 918,
        "SwarmlingMaxHP": 1588,
        "SwarmlingMaxArmor": 405,
        "GiantWaves": 9,
        "GiantCount": 33,
        "GiantMaxHP": 31869,
        "GiantMaxArmor": 309,
        "MonstersBeforeWave12": 276,
        "MarkedMonsterCount": 77,
        "AbandonedDwellingCount": 1,
        "DropHolderCount": 3,
        "ManaShardCount": 4,
        "RainCount": 1,
        "ShrineCount": 1,
        "requirements": [
            ["Field_G2"],
            ["Field_K3"],
            ["Field_G1"],
        ],
    },
    "J3": {
        "type": "NORMAL",
        "WaveCount": 56,
        "AvailableGems": ["ARMOR_TEARING", "POISON", "SLOWING"],
        "AmplifierCount": 4,
        "TowerCount": 1,
        "MonsterCount": 1128,
        "ReaverWaves": 16,
        "ReaverCount": 191,
        "ReaverMaxHP": 3752,
        "ReaverMaxArmor": 353,
        "SwarmlingWaves": 28,
        "SwarmlingCount": 891,
        "SwarmlingMaxHP": 2134,
        "SwarmlingMaxArmor": 496,
        "GiantWaves": 12,
        "GiantCount": 46,
        "GiantMaxHP": 73384,
        "GiantMaxArmor": 600,
        "MonstersBeforeWave12": 275,
        "MarkedMonsterCount": 62,
        "RainCount": 1,
        "TombCount": 1,
        "requirements": [
            ["Field_J1"],
            ["Field_Z5"],
            ["Field_J2"],
        ],
    },
    "J4": {
        "type": "TILE_GIVING",
        "WaveCount": 58,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "ARMOR_TEARING"],
        "MonsterCount": 1200,
        "ReaverWaves": 15,
        "ReaverCount": 182,
        "ReaverMaxHP": 6103,
        "ReaverMaxArmor": 689,
        "SwarmlingWaves": 30,
        "SwarmlingCount": 974,
        "SwarmlingMaxHP": 2551,
        "SwarmlingMaxArmor": 740,
        "GiantWaves": 13,
        "GiantCount": 44,
        "GiantMaxHP": 75210,
        "GiantMaxArmor": 771,
        "MonstersBeforeWave12": 189,
        "MarkedMonsterCount": 85,
        "BeaconCount": 10,
        "ManaShardCount": 4,
        "RainCount": 1,
        "ShrineCount": 1,
        "requirements": [
            ["Field_J3"],
            ["Field_G4"],
            ["Field_G3"],
        ],
    },
    "K1": {
        "type": "STORY_RELATED",
        "WaveCount": 46,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "ARMOR_TEARING"],
        "LanternCount": 4,
        "MonsterCount": 569,
        "ReaverWaves": 21,
        "ReaverCount": 248,
        "ReaverMaxHP": 1374,
        "ReaverMaxArmor": 192,
        "SwarmlingWaves": 8,
        "SwarmlingCount": 265,
        "SwarmlingMaxHP": 497,
        "SwarmlingMaxArmor": 180,
        "GiantWaves": 17,
        "GiantCount": 56,
        "GiantMaxHP": 21131,
        "GiantMaxArmor": 267,
        "MonstersBeforeWave12": 155,
        "MarkedMonsterCount": 33,
        "WatchtowerCount": 1,
        "requirements": [
            ["Field_L1"],
            ["Field_X4"],
            ["Field_K4"],
        ],
    },
    "K2": {
        "type": "NORMAL",
        "WaveCount": 46,
        "AvailableGems": ["MANA_LEECHING", "SLOWING"],
        "TowerCount": 2,
        "OldWallCount": 64,
        "MonsterCount": 564,
        "ReaverWaves": 17,
        "ReaverCount": 214,
        "ReaverMaxHP": 1080,
        "ReaverMaxArmor": 123,
        "SwarmlingWaves": 8,
        "SwarmlingCount": 274,
        "SwarmlingMaxHP": 392,
        "SwarmlingMaxArmor": 116,
        "GiantWaves": 21,
        "GiantCount": 76,
        "GiantMaxHP": 17609,
        "GiantMaxArmor": 183,
        "MonstersBeforeWave12": 135,
        "MarkedMonsterCount": 13,
        "BarricadeCount": 6,
        "requirements": [
            ["Field_X4"],
            ["Field_L1"],
            ["Field_K4"],
        ],
    },
    "K3": {
        "type": "NORMAL",
        "WaveCount": 50,
        "AvailableGems": ["BLEEDING", "POISON"],
        "MonsterCount": 631,
        "ReaverWaves": 22,
        "ReaverCount": 263,
        "ReaverMaxHP": 1943,
        "ReaverMaxArmor": 252,
        "SwarmlingWaves": 8,
        "SwarmlingCount": 296,
        "SwarmlingMaxHP": 487,
        "SwarmlingMaxArmor": 168,
        "GiantWaves": 20,
        "GiantCount": 72,
        "GiantMaxHP": 37303,
        "GiantMaxArmor": 429,
        "MonstersBeforeWave12": 115,
        "MarkedMonsterCount": 14,
        "ManaShardCount": 1,
        "MonsterNestCount": 1,
        "requirements": [
            ["Field_K5"],
            ["Field_Z4"],
            ["Field_L4"],
            ["Field_X2"],
        ],
    },
    "K4": {
        "type": "EPIC",
        "WaveCount": 46,
        "AvailableGems": ["MANA_LEECHING", "BLEEDING", "ARMOR_TEARING", "SLOWING"],
        "TowerCount": 3,
        "MonsterCount": 495,
        "ReaverWaves": 17,
        "ReaverCount": 218,
        "ReaverMaxHP": 1074,
        "ReaverMaxArmor": 134,
        "SwarmlingWaves": 7,
        "SwarmlingCount": 193,
        "SwarmlingMaxHP": 219,
        "SwarmlingMaxArmor": 74,
        "GiantWaves": 22,
        "GiantCount": 84,
        "GiantMaxHP": 14562,
        "GiantMaxArmor": 169,
        "MonstersBeforeWave12": 168,
        "MarkedMonsterCount": 4,
        "SwarmQueenCount": 1,
        "requirements": [
            ["Field_Z1"],
            ["Field_X3"],
            ["Field_X1"],
        ],
    },
    "K5": {
        "type": "SECRET",
        "WaveCount": 54,
        "AvailableGems": ["CRITHIT", "POISON"],
        "MonsterCount": 753,
        "ReaverWaves": 48,
        "ReaverCount": 586,
        "ReaverMaxHP": 4372,
        "ReaverMaxArmor": 554,
        "SwarmlingWaves": 6,
        "SwarmlingCount": 167,
        "SwarmlingMaxHP": 1567,
        "SwarmlingMaxArmor": 516,
        "MonstersBeforeWave12": 135,
        "MarkedMonsterCount": 26,
        "MonsterNestCount": 5,
        "requirements": [
            ["Field_L2"],
            ["Field_Z3"],
            ["Field_L3"],
        ],
    },
    "L1": {
        "type": "NORMAL",
        "WaveCount": 44,
        "AvailableGems": ["CRITHIT", "BLEEDING"],
        "MonsterCount": 414,
        "ReaverWaves": 21,
        "ReaverCount": 265,
        "ReaverMaxHP": 1251,
        "ReaverMaxArmor": 113,
        "SwarmlingWaves": 2,
        "SwarmlingCount": 68,
        "SwarmlingMaxHP": 86,
        "SwarmlingMaxArmor": 25,
        "GiantWaves": 21,
        "GiantCount": 81,
        "GiantMaxHP": 19334,
        "GiantMaxArmor": 160,
        "MonstersBeforeWave12": 106,
        "MarkedMonsterCount": 12,
        "BeaconCount": 4,
        "MonsterNestCount": 5,
        "RainCount": 1,
        "requirements": [
            ["Field_X1"],
            ["Field_Z1"],
            ["Field_X3"],
        ],
    },
    "L2": {
        "type": "NORMAL",
        "WaveCount": 46,
        "AvailableGems": ["POISON", "SLOWING"],
        "MonsterCount": 478,
        "ReaverWaves": 10,
        "ReaverCount": 134,
        "ReaverMaxHP": 1074,
        "ReaverMaxArmor": 112,
        "SwarmlingWaves": 6,
        "SwarmlingCount": 224,
        "SwarmlingMaxHP": 480,
        "SwarmlingMaxArmor": 128,
        "GiantWaves": 30,
        "GiantCount": 120,
        "GiantMaxHP": 23834,
        "GiantMaxArmor": 221,
        "MonstersBeforeWave12": 98,
        "DropHolderCount": 1,
        "RainCount": 1,
        "requirements": [
            ["Field_K2"],
            ["Field_K1"],
            ["Field_Z2"],
        ],
    },
    "L3": {
        "type": "NORMAL",
        "WaveCount": 46,
        "AvailableGems": ["MANA_LEECHING", "ARMOR_TEARING"],
        "TowerCount": 4,
        "MonsterCount": 563,
        "ReaverWaves": 25,
        "ReaverCount": 289,
        "ReaverMaxHP": 1672,
        "ReaverMaxArmor": 171,
        "SwarmlingWaves": 6,
        "SwarmlingCount": 216,
        "SwarmlingMaxHP": 815,
        "SwarmlingMaxArmor": 210,
        "GiantWaves": 15,
        "GiantCount": 58,
        "GiantMaxHP": 28046,
        "GiantMaxArmor": 257,
        "MonstersBeforeWave12": 139,
        "MarkedMonsterCount": 5,
        "BarricadeCount": 6,
        "ManaShardCount": 3,
        "RainCount": 1,
        "ShrineCount": 1,
        "requirements": [
            ["Field_Z2"],
            ["Field_K2"],
            ["Field_K1"],
        ],
    },
    "L4": {
        "type": "EPIC",
        "WaveCount": 50,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "ARMOR_TEARING", "POISON"],
        "TowerCount": 6,
        "MonsterCount": 483,
        "ReaverWaves": 18,
        "ReaverCount": 201,
        "ReaverMaxHP": 1894,
        "ReaverMaxArmor": 225,
        "SwarmlingWaves": 7,
        "SwarmlingCount": 194,
        "SwarmlingMaxHP": 510,
        "SwarmlingMaxArmor": 160,
        "GiantWaves": 25,
        "GiantCount": 88,
        "GiantMaxHP": 33810,
        "GiantMaxArmor": 359,
        "MonstersBeforeWave12": 90,
        "MarkedMonsterCount": 3,
        "BarricadeCount": 4,
        "WizardHunterCount": 1,
        "requirements": [
            ["Field_Z3"],
            ["Field_L2"],
            ["Field_L3"],
        ],
    },
    "L5": {
        "type": "EPIC",
        "WaveCount": 64,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING", "SLOWING"],
        "MonsterCount": 870,
        "ReaverWaves": 34,
        "ReaverCount": 443,
        "ReaverMaxHP": 9522,
        "ReaverMaxArmor": 528,
        "SwarmlingWaves": 10,
        "SwarmlingCount": 345,
        "SwarmlingMaxHP": 1922,
        "SwarmlingMaxArmor": 300,
        "GiantWaves": 20,
        "GiantCount": 82,
        "GiantMaxHP": 110184,
        "GiantMaxArmor": 567,
        "MonstersBeforeWave12": 149,
        "MarkedMonsterCount": 19,
        "MonsterNestCount": 2,
        "WizardTowerCount": 1,
        "requirements": [
            ["Field_E2", "sBeam", "sBolt", "sBarrage", "sFreeze"],
            ["Field_M3", "sBeam", "sBolt", "sBarrage", "sFreeze"],
            ["Field_M2", "sBeam", "sBolt", "sBarrage", "sFreeze"],
        ],
    },
    "M1": {
        "type": "NORMAL",
        "WaveCount": 60,
        "AvailableGems": ["MANA_LEECHING", "BLEEDING", "SLOWING"],
        "MonsterCount": 953,
        "ReaverWaves": 20,
        "ReaverCount": 239,
        "ReaverMaxHP": 4251,
        "ReaverMaxArmor": 294,
        "SwarmlingWaves": 20,
        "SwarmlingCount": 635,
        "SwarmlingMaxHP": 1255,
        "SwarmlingMaxArmor": 233,
        "GiantWaves": 20,
        "GiantCount": 79,
        "GiantMaxHP": 65392,
        "GiantMaxArmor": 405,
        "MonstersBeforeWave12": 139,
        "MarkedMonsterCount": 40,
        "AbandonedDwellingCount": 5,
        "MonsterNestCount": 5,
        "RainCount": 1,
        "requirements": [
            ["Field_J3"],
            ["Field_G3"],
            ["Field_G4"],
        ],
    },
    "M2": {
        "type": "NORMAL",
        "WaveCount": 62,
        "AvailableGems": ["CRITHIT", "POISON", "SLOWING"],
        "MonsterCount": 1031,
        "ReaverWaves": 20,
        "ReaverCount": 240,
        "ReaverMaxHP": 5208,
        "ReaverMaxArmor": 350,
        "SwarmlingWaves": 21,
        "SwarmlingCount": 718,
        "SwarmlingMaxHP": 1760,
        "SwarmlingMaxArmor": 311,
        "GiantWaves": 21,
        "GiantCount": 73,
        "GiantMaxHP": 69963,
        "GiantMaxArmor": 429,
        "MonstersBeforeWave12": 238,
        "MarkedMonsterCount": 90,
        "MonsterNestCount": 3,
        "RainCount": 1,
        "requirements": [
            ["Field_F1"],
            ["Field_J4"],
            ["Field_M1"],
        ],
    },
    "M3": {
        "type": "NORMAL",
        "WaveCount": 64,
        "AvailableGems": ["MANA_LEECHING", "ARMOR_TEARING", "POISON"],
        "LanternCount": 2,
        "AmplifierCount": 2,
        "TowerCount": 5,
        "MonsterCount": 1090,
        "ReaverWaves": 20,
        "ReaverCount": 238,
        "ReaverMaxHP": 6247,
        "ReaverMaxArmor": 393,
        "SwarmlingWaves": 22,
        "SwarmlingCount": 764,
        "SwarmlingMaxHP": 1611,
        "SwarmlingMaxArmor": 277,
        "GiantWaves": 22,
        "GiantCount": 88,
        "GiantMaxHP": 73298,
        "GiantMaxArmor": 429,
        "MonstersBeforeWave12": 207,
        "MarkedMonsterCount": 22,
        "AbandonedDwellingCount": 2,
        "BarricadeCount": 7,
        "DropHolderCount": 1,
        "ManaShardCount": 2,
        "RainCount": 1,
        "TombCount": 2,
        "requirements": [
            ["Field_J4"],
            ["Field_F1"],
            ["Field_M1"],
        ],
    },
    "M4": {
        "type": "NORMAL",
        "WaveCount": 66,
        "AvailableGems": ["BLEEDING", "ARMOR_TEARING", "POISON"],
        "MonsterCount": 1200,
        "ReaverWaves": 24,
        "ReaverCount": 288,
        "ReaverMaxHP": 6836,
        "ReaverMaxArmor": 416,
        "SwarmlingWaves": 22,
        "SwarmlingCount": 840,
        "SwarmlingMaxHP": 2159,
        "SwarmlingMaxArmor": 350,
        "GiantWaves": 20,
        "GiantCount": 72,
        "GiantMaxHP": 105153,
        "GiantMaxArmor": 572,
        "MonstersBeforeWave12": 191,
        "MarkedMonsterCount": 52,
        "RainCount": 1,
        "ShrineCount": 1,
        "requirements": [
            ["Field_L5"],
            ["Field_H1"],
            ["Field_F2"],
            ["Field_H3"],
        ],
    },
    "N1": {
        "type": "NORMAL",
        "WaveCount": 35,
        "AvailableGems": ["MANA_LEECHING", "SLOWING"],
        "MonsterCount": 671,
        "ReaverWaves": 23,
        "ReaverCount": 302,
        "ReaverMaxHP": 602,
        "ReaverMaxArmor": 100,
        "SwarmlingWaves": 10,
        "SwarmlingCount": 364,
        "SwarmlingMaxHP": 200,
        "SwarmlingMaxArmor": 87,
        "GiantWaves": 2,
        "GiantCount": 5,
        "GiantMaxHP": 5046,
        "GiantMaxArmor": 85,
        "MonstersBeforeWave12": 190,
        "MarkedMonsterCount": 27,
        "RainCount": 1,
        "requirements": [
            ["Field_R5"],
            ["Field_O3"],
            ["Field_Y1"],
        ],
    },
    "N2": {
        "type": "NORMAL",
        "WaveCount": 36,
        "AvailableGems": ["BLEEDING", "POISON"],
        "WallCount": 6,
        "MonsterCount": 587,
        "ReaverWaves": 24,
        "ReaverCount": 306,
        "ReaverMaxHP": 608,
        "ReaverMaxArmor": 93,
        "SwarmlingWaves": 8,
        "SwarmlingCount": 270,
        "SwarmlingMaxHP": 275,
        "SwarmlingMaxArmor": 107,
        "GiantWaves": 4,
        "GiantCount": 11,
        "GiantMaxHP": 3220,
        "GiantMaxArmor": 55,
        "MonstersBeforeWave12": 183,
        "MarkedMonsterCount": 49,
        "BarricadeCount": 16,
        "ManaShardCount": 2,
        "RainCount": 1,
        "requirements": [
            ["Field_Y1"],
            ["Field_R5"],
            ["Field_O3"],
        ],
    },
    "N3": {
        "type": "NORMAL",
        "WaveCount": 38,
        "AvailableGems": ["CRITHIT", "ARMOR_TEARING"],
        "MonsterCount": 532,
        "ReaverWaves": 26,
        "ReaverCount": 325,
        "ReaverMaxHP": 862,
        "ReaverMaxArmor": 122,
        "SwarmlingWaves": 6,
        "SwarmlingCount": 186,
        "SwarmlingMaxHP": 210,
        "SwarmlingMaxArmor": 81,
        "GiantWaves": 6,
        "GiantCount": 21,
        "GiantMaxHP": 10623,
        "GiantMaxArmor": 143,
        "MonstersBeforeWave12": 189,
        "MarkedMonsterCount": 32,
        "ManaShardCount": 2,
        "MonsterNestCount": 2,
        "RainCount": 1,
        "ShrineCount": 1,
        "requirements": [
            ["Field_R6"],
            ["Field_P1"],
            ["Field_O2"],
        ],
    },
    "N4": {
        "type": "NORMAL",
        "WaveCount": 70,
        "AvailableGems": ["BLEEDING", "ARMOR_TEARING", "POISON"],
        "MonsterCount": 1125,
        "ReaverWaves": 24,
        "ReaverCount": 290,
        "ReaverMaxHP": 9160,
        "ReaverMaxArmor": 526,
        "SwarmlingWaves": 23,
        "SwarmlingCount": 748,
        "SwarmlingMaxHP": 3793,
        "SwarmlingMaxArmor": 557,
        "GiantWaves": 23,
        "GiantCount": 87,
        "GiantMaxHP": 123064,
        "GiantMaxArmor": 642,
        "MonstersBeforeWave12": 122,
        "MarkedMonsterCount": 39,
        "MonsterNestCount": 2,
        "RainCount": 1,
        "requirements": [
            ["Field_H5"],
            ["Field_M4"],
            ["Field_H2"],
        ],
    },
    "N5": {
        "type": "NORMAL",
        "WaveCount": 68,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "SLOWING"],
        "PylonCount": 1,
        "AmplifierCount": 1,
        "OldWallCount": 62,
        "MonsterCount": 1104,
        "ReaverWaves": 22,
        "ReaverCount": 283,
        "ReaverMaxHP": 8747,
        "ReaverMaxArmor": 496,
        "SwarmlingWaves": 23,
        "SwarmlingCount": 743,
        "SwarmlingMaxHP": 2582,
        "SwarmlingMaxArmor": 393,
        "GiantWaves": 23,
        "GiantCount": 78,
        "GiantMaxHP": 117501,
        "GiantMaxArmor": 606,
        "MonstersBeforeWave12": 231,
        "RainCount": 1,
        "requirements": [
            ["Field_M4"],
            ["Field_H2"],
            ["Field_H5"],
        ],
    },
    "O1": {
        "type": "NORMAL",
        "WaveCount": 34,
        "AvailableGems": ["MANA_LEECHING", "POISON"],
        "MonsterCount": 516,
        "ReaverWaves": 25,
        "ReaverCount": 304,
        "ReaverMaxHP": 552,
        "ReaverMaxArmor": 75,
        "SwarmlingWaves": 6,
        "SwarmlingCount": 202,
        "SwarmlingMaxHP": 252,
        "SwarmlingMaxArmor": 87,
        "GiantWaves": 3,
        "GiantCount": 10,
        "GiantMaxHP": 8611,
        "GiantMaxArmor": 109,
        "MonstersBeforeWave12": 182,
        "MarkedMonsterCount": 2,
        "RainCount": 1,
        "requirements": [
            ["Field_N1"],
            ["Field_N2"],
            ["Field_O4"],
        ],
    },
    "O2": {
        "type": "NORMAL",
        "WaveCount": 35,
        "AvailableGems": ["CRITHIT", "ARMOR_TEARING"],
        "MonsterCount": 509,
        "ReaverWaves": 26,
        "ReaverCount": 339,
        "ReaverMaxHP": 737,
        "ReaverMaxArmor": 94,
        "SwarmlingWaves": 5,
        "SwarmlingCount": 155,
        "SwarmlingMaxHP": 263,
        "SwarmlingMaxArmor": 87,
        "GiantWaves": 4,
        "GiantCount": 15,
        "GiantMaxHP": 8294,
        "GiantMaxArmor": 102,
        "MonstersBeforeWave12": 173,
        "MarkedMonsterCount": 4,
        "BarricadeCount": 14,
        "BeaconCount": 6,
        "DropHolderCount": 1,
        "RainCount": 1,
        "requirements": [
            ["Field_O1"],
            ["Field_T5"],
            ["Field_Y2"],
        ],
    },
    "O3": {
        "type": "NORMAL",
        "WaveCount": 32,
        "AvailableGems": ["BLEEDING", "POISON"],
        "MonsterCount": 454,
        "ReaverWaves": 26,
        "ReaverCount": 305,
        "ReaverMaxHP": 478,
        "ReaverMaxArmor": 75,
        "SwarmlingWaves": 4,
        "SwarmlingCount": 141,
        "SwarmlingMaxHP": 40,
        "SwarmlingMaxArmor": 18,
        "GiantWaves": 2,
        "GiantCount": 8,
        "GiantMaxHP": 5462,
        "GiantMaxArmor": 84,
        "MonstersBeforeWave12": 203,
        "MarkedMonsterCount": 13,
        "MonsterNestCount": 1,
        "RainCount": 1,
        "requirements": [
            ["Field_R3"],
            ["Field_R4"],
            ["Field_Y3"],
        ],
    },
    "O4": {
        "type": "EPIC",
        "WaveCount": 33,
        "AvailableGems": ["MANA_LEECHING", "ARMOR_TEARING", "POISON", "SLOWING"],
        "PylonCount": 1,
        "AmplifierCount": 1,
        "TowerCount": 1,
        "WallCount": 7,
        "OldWallCount": 23,
        "MonsterCount": 445,
        "ReaverWaves": 21,
        "ReaverCount": 252,
        "ReaverMaxHP": 453,
        "ReaverMaxArmor": 61,
        "SwarmlingWaves": 6,
        "SwarmlingCount": 170,
        "SwarmlingMaxHP": 189,
        "SwarmlingMaxArmor": 65,
        "GiantWaves": 6,
        "GiantCount": 23,
        "GiantMaxHP": 7590,
        "GiantMaxArmor": 95,
        "MonstersBeforeWave12": 134,
        "AbandonedDwellingCount": 6,
        "BarricadeCount": 9,
        "DropHolderCount": 2,
        "MonsterNestCount": 4,
        "RainCount": 1,
        "requirements": [
            ["Field_O3"],
            ["Field_Y1"],
            ["Field_R5"],
        ],
    },
    "P1": {
        "type": "NORMAL",
        "WaveCount": 38,
        "AvailableGems": ["MANA_LEECHING", "SLOWING"],
        "MonsterCount": 524,
        "ReaverWaves": 26,
        "ReaverCount": 332,
        "ReaverMaxHP": 793,
        "ReaverMaxArmor": 122,
        "SwarmlingWaves": 5,
        "SwarmlingCount": 163,
        "SwarmlingMaxHP": 97,
        "SwarmlingMaxArmor": 44,
        "GiantWaves": 7,
        "GiantCount": 29,
        "GiantMaxHP": 9056,
        "GiantMaxArmor": 134,
        "MonstersBeforeWave12": 121,
        "MarkedMonsterCount": 29,
        "RainCount": 1,
        "requirements": [
            ["Field_T5"],
            ["Field_O1"],
            ["Field_Y2"],
        ],
    },
    "P2": {
        "type": "NORMAL",
        "WaveCount": 42,
        "AvailableGems": ["ARMOR_TEARING", "SLOWING"],
        "LanternCount": 3,
        "TowerCount": 6,
        "MonsterCount": 515,
        "ReaverWaves": 27,
        "ReaverCount": 335,
        "ReaverMaxHP": 1126,
        "ReaverMaxArmor": 160,
        "SwarmlingWaves": 4,
        "SwarmlingCount": 137,
        "SwarmlingMaxHP": 346,
        "SwarmlingMaxArmor": 131,
        "GiantWaves": 11,
        "GiantCount": 43,
        "GiantMaxHP": 11011,
        "GiantMaxArmor": 152,
        "MonstersBeforeWave12": 141,
        "BeaconCount": 1,
        "MonsterNestCount": 1,
        "RainCount": 1,
        "requirements": [
            ["Field_P3"],
            ["Field_N3"],
            ["Field_Y4"],
        ],
    },
    "P3": {
        "type": "NORMAL",
        "WaveCount": 40,
        "AvailableGems": ["CRITHIT", "ARMOR_TEARING"],
        "MonsterCount": 495,
        "ReaverWaves": 27,
        "ReaverCount": 318,
        "ReaverMaxHP": 1006,
        "ReaverMaxArmor": 140,
        "SwarmlingWaves": 4,
        "SwarmlingCount": 139,
        "SwarmlingMaxHP": 334,
        "SwarmlingMaxArmor": 122,
        "GiantWaves": 9,
        "GiantCount": 38,
        "GiantMaxHP": 13383,
        "GiantMaxArmor": 174,
        "MonstersBeforeWave12": 121,
        "RainCount": 1,
        "requirements": [
            ["Field_O2"],
            ["Field_R6"],
            ["Field_P1"],
        ],
    },
    "P4": {
        "type": "EPIC",
        "WaveCount": 40,
        "AvailableGems": ["CRITHIT", "BLEEDING", "ARMOR_TEARING", "SLOWING"],
        "MonsterCount": 394,
        "ReaverWaves": 23,
        "ReaverCount": 277,
        "ReaverMaxHP": 1126,
        "ReaverMaxArmor": 140,
        "SwarmlingWaves": 2,
        "SwarmlingCount": 63,
        "SwarmlingMaxHP": 149,
        "SwarmlingMaxArmor": 54,
        "GiantWaves": 15,
        "GiantCount": 54,
        "GiantMaxHP": 14993,
        "GiantMaxArmor": 174,
        "MonstersBeforeWave12": 115,
        "MarkedMonsterCount": 9,
        "BarricadeCount": 12,
        "MonsterNestCount": 1,
        "RainCount": 1,
        "requirements": [
            ["Field_N3"],
            ["Field_Y4"],
            ["Field_P5"],
            ["Field_P3"],
        ],
    },
    "P5": {
        "type": "NORMAL",
        "WaveCount": 40,
        "AvailableGems": ["MANA_LEECHING", "POISON"],
        "MonsterCount": 1265,
        "ReaverWaves": 5,
        "ReaverCount": 61,
        "ReaverMaxHP": 457,
        "ReaverMaxArmor": 93,
        "SwarmlingWaves": 33,
        "SwarmlingCount": 1194,
        "SwarmlingMaxHP": 273,
        "SwarmlingMaxArmor": 140,
        "GiantWaves": 2,
        "GiantCount": 10,
        "GiantMaxHP": 9430,
        "GiantMaxArmor": 174,
        "MonstersBeforeWave12": 348,
        "MarkedMonsterCount": 78,
        "MonsterNestCount": 1,
        "RainCount": 1,
        "requirements": [
            ["Field_P1"],
            ["Field_R6"],
            ["Field_O2"],
        ],
    },
    "P6": {
        "type": "SECRET",
        "WaveCount": 40,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING", "ARMOR_TEARING", "POISON", "SLOWING"],
        "MonsterCount": 149,
        "GiantWaves": 40,
        "GiantCount": 149,
        "GiantMaxHP": 14461,
        "GiantMaxArmor": 185,
        "MonstersBeforeWave12": 40,
        "MarkedMonsterCount": 8,
        "RainCount": 1,
        "requirements": [
            ["Field_P5"],
            ["Field_Y4"],
            ["Field_N3"],
            ["Field_P3"],
        ],
    },
    "Q1": {
        "type": "NORMAL",
        "WaveCount": 24,
        "AvailableGems": ["CRITHIT", "BLEEDING"],
        "MonsterCount": 398,
        "ReaverWaves": 20,
        "ReaverCount": 256,
        "ReaverMaxHP": 120,
        "ReaverMaxArmor": 18,
        "SwarmlingWaves": 4,
        "SwarmlingCount": 142,
        "SwarmlingMaxHP": 50,
        "SwarmlingMaxArmor": 19,
        "MonstersBeforeWave12": 175,
        "ApparitionCount": 1,
        "requirements": [
            ["Field_R2"],
            ["Field_V3"],
            ["Field_Q2"],
        ],
    },
    "Q2": {
        "type": "NORMAL",
        "WaveCount": 22,
        "AvailableGems": ["CRITHIT", "POISON"],
        "LanternCount": 1,
        "AmplifierCount": 1,
        "TowerCount": 2,
        "MonsterCount": 374,
        "ReaverWaves": 16,
        "ReaverCount": 196,
        "ReaverMaxHP": 121,
        "ReaverMaxArmor": 25,
        "SwarmlingWaves": 6,
        "SwarmlingCount": 178,
        "SwarmlingMaxHP": 43,
        "SwarmlingMaxArmor": 23,
        "MonstersBeforeWave12": 152,
        "BarricadeCount": 6,
        "requirements": [
            ["Field_S4"],
            ["Field_V2"],
            ["Field_R1"],
        ],
    },
    "Q3": {
        "type": "NORMAL",
        "WaveCount": 24,
        "AvailableGems": ["ARMOR_TEARING", "SLOWING"],
        "PylonCount": 1,
        "TowerCount": 2,
        "MonsterCount": 379,
        "ReaverWaves": 19,
        "ReaverCount": 241,
        "ReaverMaxHP": 151,
        "ReaverMaxArmor": 33,
        "SwarmlingWaves": 4,
        "SwarmlingCount": 133,
        "SwarmlingMaxHP": 63,
        "SwarmlingMaxArmor": 35,
        "GiantWaves": 1,
        "GiantCount": 5,
        "GiantMaxHP": 2530,
        "GiantMaxArmor": 54,
        "MonstersBeforeWave12": 166,
        "requirements": [
            ["Field_T1"],
            ["Field_V4"],
            ["Field_Q1"],
        ],
    },
    "Q4": {
        "type": "EPIC",
        "WaveCount": 26,
        "AvailableGems": ["BLEEDING", "SLOWING"],
        "LanternCount": 2,
        "TowerCount": 2,
        "WallCount": 7,
        "OldWallCount": 19,
        "MonsterCount": 396,
        "ReaverWaves": 21,
        "ReaverCount": 264,
        "ReaverMaxHP": 171,
        "ReaverMaxArmor": 43,
        "SwarmlingWaves": 4,
        "SwarmlingCount": 128,
        "SwarmlingMaxHP": 57,
        "SwarmlingMaxArmor": 38,
        "GiantWaves": 1,
        "GiantCount": 4,
        "GiantMaxHP": 2286,
        "GiantMaxArmor": 58,
        "MonstersBeforeWave12": 185,
        "AbandonedDwellingCount": 5,
        "BarricadeCount": 4,
        "DropHolderCount": 3,
        "RainCount": 1,
        "SnowCount": 1,
        "requirements": [
            ["Field_T4"],
            ["Field_U3"],
            ["Field_Q3"],
        ],
    },
    "Q5": {
        "type": "NORMAL",
        "WaveCount": 26,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "POISON"],
        "TrapCount": 4,
        "MonsterCount": 405,
        "ReaverWaves": 20,
        "ReaverCount": 230,
        "ReaverMaxHP": 192,
        "ReaverMaxArmor": 33,
        "SwarmlingWaves": 5,
        "SwarmlingCount": 172,
        "SwarmlingMaxHP": 63,
        "SwarmlingMaxArmor": 28,
        "GiantWaves": 1,
        "GiantCount": 3,
        "GiantMaxHP": 2559,
        "GiantMaxArmor": 44,
        "MonstersBeforeWave12": 151,
        "MarkedMonsterCount": 12,
        "BarricadeCount": 11,
        "requirements": [
            ["Field_Q4"],
            ["Field_U1"],
            ["Field_U4"],
        ],
    },
    "R1": {
        "type": "NORMAL",
        "WaveCount": 22,
        "AvailableGems": ["MANA_LEECHING", "ARMOR_TEARING"],
        "LanternCount": 2,
        "AmplifierCount": 1,
        "WallCount": 14,
        "OldWallCount": 11,
        "MonsterCount": 339,
        "ReaverWaves": 17,
        "ReaverCount": 205,
        "ReaverMaxHP": 93,
        "ReaverMaxArmor": 8,
        "SwarmlingWaves": 5,
        "SwarmlingCount": 134,
        "SwarmlingMaxHP": 39,
        "SwarmlingMaxArmor": 8,
        "MonstersBeforeWave12": 174,
        "BarricadeCount": 11,
        "requirements": [
            ["Field_V1"],
            ["Field_S2"],
            ["Field_S1"],
        ],
    },
    "R2": {
        "type": "EPIC",
        "WaveCount": 22,
        "AvailableGems": ["BLEEDING", "POISON"],
        "TrapCount": 4,
        "MonsterCount": 409,
        "ReaverWaves": 16,
        "ReaverCount": 202,
        "ReaverMaxHP": 93,
        "ReaverMaxArmor": 15,
        "SwarmlingWaves": 6,
        "SwarmlingCount": 207,
        "SwarmlingMaxHP": 39,
        "SwarmlingMaxArmor": 17,
        "MonstersBeforeWave12": 205,
        "requirements": [
            ["Field_S4"],
            ["Field_V2"],
            ["Field_R1"],
        ],
    },
    "R3": {
        "type": "NORMAL",
        "WaveCount": 30,
        "AvailableGems": ["MANA_LEECHING", "BLEEDING"],
        "MonsterCount": 495,
        "ReaverWaves": 24,
        "ReaverCount": 318,
        "ReaverMaxHP": 261,
        "ReaverMaxArmor": 33,
        "SwarmlingWaves": 5,
        "SwarmlingCount": 173,
        "SwarmlingMaxHP": 75,
        "SwarmlingMaxArmor": 26,
        "GiantWaves": 1,
        "GiantCount": 4,
        "GiantMaxHP": 3249,
        "GiantMaxArmor": 43,
        "MonstersBeforeWave12": 169,
        "MarkedMonsterCount": 11,
        "BarricadeCount": 16,
        "RainCount": 1,
        "requirements": [
            ["Field_T3"],
            ["Field_Q5"],
            ["Field_U2"],
            ["Field_T2"],
        ],
    },
    "R4": {
        "type": "NORMAL",
        "WaveCount": 30,
        "AvailableGems": ["ARMOR_TEARING", "SLOWING"],
        "PylonCount": 2,
        "TowerCount": 3,
        "MonsterCount": 495,
        "ReaverWaves": 24,
        "ReaverCount": 318,
        "ReaverMaxHP": 335,
        "ReaverMaxArmor": 57,
        "SwarmlingWaves": 5,
        "SwarmlingCount": 173,
        "SwarmlingMaxHP": 96,
        "SwarmlingMaxArmor": 43,
        "GiantWaves": 1,
        "GiantCount": 4,
        "GiantMaxHP": 4140,
        "GiantMaxArmor": 70,
        "MonstersBeforeWave12": 169,
        "MarkedMonsterCount": 11,
        "AbandonedDwellingCount": 2,
        "ShrineCount": 1,
        "requirements": [
            ["Field_Q5"],
            ["Field_U2"],
            ["Field_T3"],
            ["Field_T2"],
        ],
    },
    "R5": {
        "type": "EPIC",
        "WaveCount": 32,
        "AvailableGems": ["CRITHIT", "POISON"],
        "PylonCount": 4,
        "TowerCount": 2,
        "MonsterCount": 509,
        "ReaverWaves": 22,
        "ReaverCount": 272,
        "ReaverMaxHP": 403,
        "ReaverMaxArmor": 61,
        "SwarmlingWaves": 6,
        "SwarmlingCount": 222,
        "SwarmlingMaxHP": 134,
        "SwarmlingMaxArmor": 53,
        "GiantWaves": 4,
        "GiantCount": 15,
        "GiantMaxHP": 6253,
        "GiantMaxArmor": 89,
        "MonstersBeforeWave12": 144,
        "MarkedMonsterCount": 15,
        "requirements": [
            ["Field_Y3"],
            ["Field_R4"],
            ["Field_R3"],
        ],
    },
    "R6": {
        "type": "SECRET",
        "WaveCount": 36,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING"],
        "AmplifierCount": 6,
        "TowerCount": 1,
        "MonsterCount": 392,
        "ReaverWaves": 12,
        "ReaverCount": 135,
        "ReaverMaxHP": 362,
        "ReaverMaxArmor": 70,
        "SwarmlingWaves": 6,
        "SwarmlingCount": 189,
        "SwarmlingMaxHP": 248,
        "SwarmlingMaxArmor": 117,
        "GiantWaves": 18,
        "GiantCount": 68,
        "GiantMaxHP": 9991,
        "GiantMaxArmor": 167,
        "MonstersBeforeWave12": 169,
        "AbandonedDwellingCount": 2,
        "ApparitionCount": 1,
        "MonsterNestCount": 3,
        "RainCount": 1,
        "requirements": [
            ["Field_O1"],
            ["Field_Y2"],
            ["Field_T5"],
        ],
    },
    "S1": {
        "type": "NORMAL",
        "WaveCount": 14,
        "AvailableGems": ["MANA_LEECHING", "SLOWING"],
        "TrapCount": 4,
        "MonsterCount": 172,
        "ReaverWaves": 14,
        "ReaverCount": 172,
        "ReaverMaxHP": 44,
        "ReaverMaxArmor": 10,
        "MonstersBeforeWave12": 137,
        "MonsterNestCount": 1,
        "requirements": [
            ["Field_W1"],
            ["Field_W2"],
            ["Field_W3"],
            ["Field_W4"],
            ["Field_S2"],
            ["Field_S3"],
            ["Field_S4"],
        ],
    },
    "S2": {
        "type": "NORMAL",
        "WaveCount": 16,
        "AvailableGems": ["MANA_LEECHING", "ARMOR_TEARING", "SLOWING"],
        "TowerCount": 1,
        "MonsterCount": 199,
        "ReaverWaves": 16,
        "ReaverCount": 199,
        "ReaverMaxHP": 57,
        "ReaverMaxArmor": 11,
        "MonstersBeforeWave12": 137,
        "AbandonedDwellingCount": 1,
        "BeaconCount": 2,
        "DropHolderCount": 1,
        "requirements": [
            ["Field_W1"],
            ["Field_W2"],
            ["Field_W3"],
            ["Field_W4"],
            ["Field_S1"],
            ["Field_S3"],
            ["Field_S4"],
        ],
    },
    "S3": {
        "type": "NORMAL",
        "WaveCount": 14,
        "AvailableGems": ["CRITHIT", "SLOWING"],
        "TrapCount": 3,
        "TowerCount": 1,
        "OldWallCount": 1,
        "MonsterCount": 165,
        "ReaverWaves": 14,
        "ReaverCount": 165,
        "ReaverMaxHP": 44,
        "ReaverMaxArmor": 10,
        "MonstersBeforeWave12": 133,
        "MonsterNestCount": 1,
        "requirements": [
            ["Field_W1"],
            ["Field_W2"],
            ["Field_W3"],
            ["Field_W4"],
            ["Field_S1"],
            ["Field_S2"],
            ["Field_S4"],
        ],
    },
    "S4": {
        "type": "EPIC",
        "WaveCount": 20,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "ARMOR_TEARING"],
        "TrapCount": 6,
        "TowerCount": 8,
        "WallCount": 22,
        "OldWallCount": 57,
        "MonsterCount": 318,
        "ReaverWaves": 17,
        "ReaverCount": 206,
        "ReaverMaxHP": 86,
        "ReaverMaxArmor": 14,
        "SwarmlingWaves": 3,
        "SwarmlingCount": 112,
        "SwarmlingMaxHP": 31,
        "SwarmlingMaxArmor": 14,
        "MonstersBeforeWave12": 135,
        "BeaconCount": 1,
        "requirements": [
            ["Field_W1"],
            ["Field_W2"],
            ["Field_W3"],
            ["Field_W4"],
            ["Field_S1"],
            ["Field_S2"],
            ["Field_S3"],
        ],
    },
    "T1": {
        "type": "NORMAL",
        "WaveCount": 26,
        "AvailableGems": ["BLEEDING", "ARMOR_TEARING"],
        "TowerCount": 1,
        "MonsterCount": 427,
        "ReaverWaves": 20,
        "ReaverCount": 250,
        "ReaverMaxHP": 219,
        "ReaverMaxArmor": 43,
        "SwarmlingWaves": 6,
        "SwarmlingCount": 177,
        "SwarmlingMaxHP": 62,
        "SwarmlingMaxArmor": 33,
        "MonstersBeforeWave12": 174,
        "MarkedMonsterCount": 11,
        "BeaconCount": 2,
        "MonsterNestCount": 2,
        "SnowCount": 1,
        "requirements": [
            ["Field_V3"],
            ["Field_Q2"],
            ["Field_R2"],
        ],
    },
    "T2": {
        "type": "STORY_RELATED",
        "WaveCount": 28,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING"],
        "AmplifierCount": 3,
        "WallCount": 16,
        "MonsterCount": 441,
        "ReaverWaves": 23,
        "ReaverCount": 298,
        "ReaverMaxHP": 251,
        "ReaverMaxArmor": 36,
        "SwarmlingWaves": 4,
        "SwarmlingCount": 140,
        "SwarmlingMaxHP": 72,
        "SwarmlingMaxArmor": 29,
        "GiantWaves": 1,
        "GiantCount": 3,
        "GiantMaxHP": 3910,
        "GiantMaxArmor": 55,
        "MonstersBeforeWave12": 147,
        "SnowCount": 1,
        "requirements": [
            ["Field_U1"],
            ["Field_U4"],
            ["Field_Q4"],
        ],
    },
    "T3": {
        "type": "NORMAL",
        "WaveCount": 28,
        "AvailableGems": ["POISON", "SLOWING"],
        "MonsterCount": 678,
        "ReaverWaves": 12,
        "ReaverCount": 145,
        "ReaverMaxHP": 266,
        "ReaverMaxArmor": 46,
        "SwarmlingWaves": 15,
        "SwarmlingCount": 529,
        "SwarmlingMaxHP": 96,
        "SwarmlingMaxArmor": 43,
        "GiantWaves": 1,
        "GiantCount": 4,
        "GiantMaxHP": 4140,
        "GiantMaxArmor": 70,
        "MonstersBeforeWave12": 233,
        "MarkedMonsterCount": 10,
        "BeaconCount": 5,
        "MonsterNestCount": 1,
        "SnowCount": 1,
        "requirements": [
            ["Field_U4"],
            ["Field_Q4"],
            ["Field_U1"],
        ],
    },
    "T4": {
        "type": "EPIC",
        "WaveCount": 30,
        "AvailableGems": ["CRITHIT", "ARMOR_TEARING", "SLOWING"],
        "MonsterCount": 742,
        "ReaverWaves": 14,
        "ReaverCount": 188,
        "ReaverMaxHP": 262,
        "ReaverMaxArmor": 35,
        "SwarmlingWaves": 16,
        "SwarmlingCount": 554,
        "SwarmlingMaxHP": 126,
        "SwarmlingMaxArmor": 43,
        "MonstersBeforeWave12": 225,
        "MarkedMonsterCount": 55,
        "AbandonedDwellingCount": 8,
        "SnowCount": 1,
        "requirements": [
            ["Field_T1"],
            ["Field_V4"],
            ["Field_Q1"],
        ],
    },
    "T5": {
        "type": "SECRET",
        "WaveCount": 40,
        "AvailableGems": ["ARMOR_TEARING", "POISON", "SLOWING"],
        "MonsterCount": 1025,
        "ReaverWaves": 12,
        "ReaverCount": 144,
        "ReaverMaxHP": 745,
        "ReaverMaxArmor": 78,
        "SwarmlingWaves": 28,
        "SwarmlingCount": 881,
        "SwarmlingMaxHP": 312,
        "SwarmlingMaxArmor": 84,
        "MonstersBeforeWave12": 260,
        "MarkedMonsterCount": 13,
        "SnowCount": 1,
        "requirements": [
            ["Field_N2"],
            ["Field_O4"],
            ["Field_N1"],
        ],
    },
    "U1": {
        "type": "NORMAL",
        "WaveCount": 30,
        "AvailableGems": ["BLEEDING", "POISON"],
        "MonsterCount": 598,
        "ReaverWaves": 20,
        "ReaverCount": 233,
        "ReaverMaxHP": 311,
        "ReaverMaxArmor": 53,
        "SwarmlingWaves": 10,
        "SwarmlingCount": 365,
        "SwarmlingMaxHP": 130,
        "SwarmlingMaxArmor": 57,
        "MonstersBeforeWave12": 194,
        "SnowCount": 1,
        "requirements": [
            ["Field_T4"],
            ["Field_Q3"],
            ["Field_U3"],
        ],
    },
    "U2": {
        "type": "NORMAL",
        "WaveCount": 32,
        "AvailableGems": ["ARMOR_TEARING", "SLOWING"],
        "MonsterCount": 761,
        "ReaverWaves": 18,
        "ReaverCount": 224,
        "ReaverMaxHP": 413,
        "ReaverMaxArmor": 65,
        "SwarmlingWaves": 14,
        "SwarmlingCount": 537,
        "SwarmlingMaxHP": 148,
        "SwarmlingMaxArmor": 61,
        "MonstersBeforeWave12": 170,
        "MarkedMonsterCount": 66,
        "SnowCount": 1,
        "requirements": [
            ["Field_U1"],
            ["Field_Q4"],
            ["Field_U4"],
        ],
    },
    "U3": {
        "type": "NORMAL",
        "WaveCount": 30,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING"],
        "MonsterCount": 758,
        "ReaverWaves": 10,
        "ReaverCount": 120,
        "ReaverMaxHP": 288,
        "ReaverMaxArmor": 37,
        "SwarmlingWaves": 20,
        "SwarmlingCount": 638,
        "SwarmlingMaxHP": 130,
        "SwarmlingMaxArmor": 43,
        "MonstersBeforeWave12": 252,
        "ManaShardCount": 2,
        "ShrineCount": 1,
        "SnowCount": 1,
        "requirements": [
            ["Field_V4"],
            ["Field_T1"],
            ["Field_Q1"],
        ],
    },
    "U4": {
        "type": "EPIC",
        "WaveCount": 30,
        "AvailableGems": ["CRITHIT", "BLEEDING", "ARMOR_TEARING"],
        "MonsterCount": 694,
        "ReaverWaves": 15,
        "ReaverCount": 174,
        "ReaverMaxHP": 304,
        "ReaverMaxArmor": 50,
        "SwarmlingWaves": 15,
        "SwarmlingCount": 520,
        "SwarmlingMaxHP": 137,
        "SwarmlingMaxArmor": 57,
        "MonstersBeforeWave12": 248,
        "AbandonedDwellingCount": 3,
        "ManaShardCount": 1,
        "MonsterNestCount": 2,
        "SnowCount": 1,
        "requirements": [
            ["Field_Q3"],
            ["Field_T4"],
            ["Field_U3"],
        ],
    },
    "V1": {
        "type": "NORMAL",
        "WaveCount": 20,
        "AvailableGems": ["ARMOR_TEARING", "POISON"],
        "MonsterCount": 343,
        "ReaverWaves": 15,
        "ReaverCount": 180,
        "ReaverMaxHP": 65,
        "ReaverMaxArmor": 14,
        "SwarmlingWaves": 5,
        "SwarmlingCount": 163,
        "SwarmlingMaxHP": 23,
        "SwarmlingMaxArmor": 14,
        "MonstersBeforeWave12": 142,
        "requirements": [
            ["Field_W4"],
            ["Field_W2"],
            ["Field_W3"],
        ],
    },
    "V2": {
        "type": "NORMAL",
        "WaveCount": 22,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING"],
        "TowerCount": 10,
        "MonsterCount": 368,
        "ReaverWaves": 16,
        "ReaverCount": 184,
        "ReaverMaxHP": 91,
        "ReaverMaxArmor": 17,
        "SwarmlingWaves": 6,
        "SwarmlingCount": 184,
        "SwarmlingMaxHP": 28,
        "SwarmlingMaxArmor": 14,
        "MonstersBeforeWave12": 163,
        "BeaconCount": 2,
        "ShrineCount": 1,
        "requirements": [
            ["Field_V1"],
            ["Field_S3"],
            ["Field_S1"],
        ],
    },
    "V3": {
        "type": "NORMAL",
        "WaveCount": 24,
        "AvailableGems": ["POISON", "SLOWING"],
        "MonsterCount": 439,
        "ReaverWaves": 17,
        "ReaverCount": 214,
        "ReaverMaxHP": 98,
        "ReaverMaxArmor": 27,
        "SwarmlingWaves": 7,
        "SwarmlingCount": 225,
        "SwarmlingMaxHP": 41,
        "SwarmlingMaxArmor": 28,
        "MonstersBeforeWave12": 204,
        "MonsterNestCount": 2,
        "requirements": [
            ["Field_V2"],
            ["Field_S4"],
            ["Field_R1"],
        ],
    },
    "V4": {
        "type": "EPIC",
        "WaveCount": 24,
        "AvailableGems": ["CRITHIT", "ARMOR_TEARING", "SLOWING"],
        "AmplifierCount": 7,
        "TowerCount": 2,
        "MonsterCount": 453,
        "ReaverWaves": 16,
        "ReaverCount": 198,
        "ReaverMaxHP": 129,
        "ReaverMaxArmor": 19,
        "SwarmlingWaves": 8,
        "SwarmlingCount": 255,
        "SwarmlingMaxHP": 43,
        "SwarmlingMaxArmor": 17,
        "MonstersBeforeWave12": 197,
        "requirements": [
            ["Field_V3"],
            ["Field_Q2"],
            ["Field_R2"],
        ],
    },
    "W1": {
        "type": "NORMAL",
        "WaveCount": 6,
        "AvailableGems": ["ARMOR_TEARING", "SLOWING"],
        "TowerCount": 5,
        "MonsterCount": 84,
        "ReaverWaves": 6,
        "ReaverCount": 84,
        "ReaverMaxHP": 9,
        "ReaverMaxArmor": 6,
        "MonstersBeforeWave12": 84,
        "requirements": [
            ["Field_W2"],
            ["Field_W3"],
            ["Field_W4"],
            ["Field_S1"],
            ["Field_S2"],
            ["Field_S3"],
            ["Field_S4"],
        ],
    },
    "W2": {
        "type": "NORMAL",
        "WaveCount": 8,
        "AvailableGems": ["ARMOR_TEARING", "POISON"],
        "TowerCount": 4,
        "MonsterCount": 110,
        "ReaverWaves": 8,
        "ReaverCount": 110,
        "ReaverMaxHP": 17,
        "ReaverMaxArmor": 6,
        "MonstersBeforeWave12": 110,
        "requirements": [
            ["Field_W1"],
            ["Field_W3"],
            ["Field_W4"],
            ["Field_S1"],
            ["Field_S2"],
            ["Field_S3"],
            ["Field_S4"],
        ],
    },
    "W3": {
        "type": "STORY_RELATED",
        "WaveCount": 12,
        "AvailableGems": ["MANA_LEECHING", "SLOWING"],
        "MonsterCount": 141,
        "ReaverWaves": 12,
        "ReaverCount": 141,
        "ReaverMaxHP": 19,
        "ReaverMaxArmor": 8,
        "MonstersBeforeWave12": 131,
        "requirements": [
            ["Field_W1"],
            ["Field_W2"],
            ["Field_W4"],
            ["Field_S1"],
            ["Field_S2"],
            ["Field_S3"],
            ["Field_S4"],
        ],
    },
    "W4": {
        "type": "EPIC",
        "WaveCount": 14,
        "AvailableGems": ["POISON"],
        "TowerCount": 8,
        "WallCount": 4,
        "MonsterCount": 173,
        "ReaverWaves": 14,
        "ReaverCount": 173,
        "ReaverMaxHP": 38,
        "ReaverMaxArmor": 10,
        "MonstersBeforeWave12": 132,
        "BarricadeCount": 6,
        "requirements": [
            ["Field_W1"],
            ["Field_W2"],
            ["Field_W3"],
            ["Field_S1"],
            ["Field_S2"],
            ["Field_S3"],
            ["Field_S4"],
        ],
    },
    "X1": {
        "type": "NORMAL",
        "WaveCount": 42,
        "AvailableGems": ["ARMOR_TEARING", "POISON"],
        "MonsterCount": 1061,
        "ReaverWaves": 14,
        "ReaverCount": 169,
        "ReaverMaxHP": 1067,
        "ReaverMaxArmor": 128,
        "SwarmlingWaves": 24,
        "SwarmlingCount": 875,
        "SwarmlingMaxHP": 357,
        "SwarmlingMaxArmor": 112,
        "GiantWaves": 4,
        "GiantCount": 17,
        "GiantMaxHP": 12348,
        "GiantMaxArmor": 140,
        "MonstersBeforeWave12": 247,
        "MarkedMonsterCount": 100,
        "JarOfWaspsCount": 1,
        "MonsterNestCount": 2,
        "SnowCount": 1,
        "requirements": [
            ["Field_P6"],
            ["Field_P4"],
            ["Field_P2"],
        ],
    },
    "X2": {
        "type": "NORMAL",
        "WaveCount": 48,
        "AvailableGems": ["MANA_LEECHING", "ARMOR_TEARING", "SLOWING"],
        "PylonCount": 1,
        "TowerCount": 1,
        "MonsterCount": 720,
        "ReaverWaves": 22,
        "ReaverCount": 253,
        "ReaverMaxHP": 1796,
        "ReaverMaxArmor": 240,
        "SwarmlingWaves": 12,
        "SwarmlingCount": 413,
        "SwarmlingMaxHP": 450,
        "SwarmlingMaxArmor": 160,
        "GiantWaves": 14,
        "GiantCount": 54,
        "GiantMaxHP": 24021,
        "GiantMaxArmor": 294,
        "MonstersBeforeWave12": 170,
        "MarkedMonsterCount": 33,
        "AbandonedDwellingCount": 6,
        "DropHolderCount": 1,
        "JarOfWaspsCount": 3,
        "SnowCount": 1,
        "requirements": [
            ["Field_L3"],
            ["Field_Z3"],
            ["Field_L2"],
        ],
    },
    "X3": {
        "type": "NORMAL",
        "WaveCount": 44,
        "AvailableGems": ["BLEEDING", "ARMOR_TEARING"],
        "LanternCount": 1,
        "AmplifierCount": 1,
        "MonsterCount": 742,
        "ReaverWaves": 23,
        "ReaverCount": 282,
        "ReaverMaxHP": 1300,
        "ReaverMaxArmor": 183,
        "SwarmlingWaves": 12,
        "SwarmlingCount": 425,
        "SwarmlingMaxHP": 468,
        "SwarmlingMaxArmor": 171,
        "GiantWaves": 9,
        "GiantCount": 35,
        "GiantMaxHP": 16172,
        "GiantMaxArmor": 211,
        "MonstersBeforeWave12": 229,
        "MarkedMonsterCount": 29,
        "AbandonedDwellingCount": 5,
        "BarricadeCount": 5,
        "ManaShardCount": 1,
        "MonsterNestCount": 1,
        "SnowCount": 1,
        "requirements": [
            ["Field_P6"],
            ["Field_P2"],
            ["Field_P4"],
        ],
    },
    "X4": {
        "type": "EPIC",
        "WaveCount": 46,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "ARMOR_TEARING", "POISON"],
        "LanternCount": 1,
        "PylonCount": 1,
        "TowerCount": 2,
        "MonsterCount": 532,
        "ReaverWaves": 29,
        "ReaverCount": 359,
        "ReaverMaxHP": 954,
        "ReaverMaxArmor": 120,
        "SwarmlingWaves": 4,
        "SwarmlingCount": 134,
        "SwarmlingMaxHP": 395,
        "SwarmlingMaxArmor": 128,
        "GiantWaves": 13,
        "GiantCount": 39,
        "GiantMaxHP": 15698,
        "GiantMaxArmor": 180,
        "MonstersBeforeWave12": 121,
        "MarkedMonsterCount": 5,
        "BeaconCount": 4,
        "ManaShardCount": 3,
        "SnowCount": 1,
        "WraithCount": 1,
        "requirements": [
            ["Field_Z1"],
            ["Field_X3"],
            ["Field_X1"],
        ],
    },
    "Y1": {
        "type": "NORMAL",
        "WaveCount": 32,
        "AvailableGems": ["BLEEDING", "POISON"],
        "MonsterCount": 708,
        "ReaverWaves": 15,
        "ReaverCount": 187,
        "ReaverMaxHP": 443,
        "ReaverMaxArmor": 57,
        "SwarmlingWaves": 15,
        "SwarmlingCount": 515,
        "SwarmlingMaxHP": 185,
        "SwarmlingMaxArmor": 61,
        "GiantWaves": 2,
        "GiantCount": 6,
        "GiantMaxHP": 5462,
        "GiantMaxArmor": 71,
        "MonstersBeforeWave12": 238,
        "SleepingHiveCount": 1,
        "SnowCount": 1,
        "requirements": [
            ["Field_Y3"],
            ["Field_R4"],
            ["Field_R3"],
        ],
    },
    "Y2": {
        "type": "NORMAL",
        "WaveCount": 35,
        "AvailableGems": ["CRITHIT", "ARMOR_TEARING"],
        "LanternCount": 1,
        "PylonCount": 2,
        "MonsterCount": 704,
        "ReaverWaves": 17,
        "ReaverCount": 234,
        "ReaverMaxHP": 457,
        "ReaverMaxArmor": 56,
        "SwarmlingWaves": 16,
        "SwarmlingCount": 464,
        "SwarmlingMaxHP": 190,
        "SwarmlingMaxArmor": 60,
        "GiantWaves": 2,
        "GiantCount": 6,
        "GiantMaxHP": 5290,
        "GiantMaxArmor": 64,
        "MonstersBeforeWave12": 199,
        "BarricadeCount": 6,
        "ManaShardCount": 1,
        "SnowCount": 1,
        "requirements": [
            ["Field_N2"],
            ["Field_O4"],
            ["Field_N1"],
        ],
    },
    "Y3": {
        "type": "STORY_RELATED",
        "WaveCount": 30,
        "AvailableGems": ["CRITHIT", "ARMOR_TEARING", "POISON"],
        "MonsterCount": 621,
        "ReaverWaves": 16,
        "ReaverCount": 196,
        "ReaverMaxHP": 380,
        "ReaverMaxArmor": 66,
        "SwarmlingWaves": 12,
        "SwarmlingCount": 416,
        "SwarmlingMaxHP": 159,
        "SwarmlingMaxArmor": 71,
        "GiantWaves": 2,
        "GiantCount": 9,
        "GiantMaxHP": 5046,
        "GiantMaxArmor": 85,
        "MonstersBeforeWave12": 225,
        "MarkedMonsterCount": 49,
        "SnowCount": 1,        
        "requirements": [
            ["Field_Q5"],
            ["Field_T2"],
            ["Field_U2"],
        ],
    },
    "Y4": {
        "type": "EPIC",
        "WaveCount": 40,
        "AvailableGems": ["CRITHIT", "MANA_LEECHING", "BLEEDING", "SLOWING"],
        "TowerCount": 6,
        "MonsterCount": 794,
        "ReaverWaves": 20,
        "ReaverCount": 233,
        "ReaverMaxHP": 966,
        "ReaverMaxArmor": 140,
        "SwarmlingWaves": 16,
        "SwarmlingCount": 544,
        "SwarmlingMaxHP": 320,
        "SwarmlingMaxArmor": 122,
        "GiantWaves": 4,
        "GiantCount": 17,
        "GiantMaxHP": 12851,
        "GiantMaxArmor": 174,
        "MonstersBeforeWave12": 178,
        "BarricadeCount": 4,
        "ManaShardCount": 1,
        "SnowCount": 1,
        "SpecterCount": 1,
        "requirements": [
            ["Field_O2"],
            ["Field_P1"],
            ["Field_R6"],
        ],
    },
    "Z1": {
        "type": "NORMAL",
        "WaveCount": 44,
        "AvailableGems": ["CRITHIT", "BLEEDING", "POISON"],
        "MonsterCount": 778,
        "ReaverWaves": 22,
        "ReaverCount": 247,
        "ReaverMaxHP": 1233,
        "ReaverMaxArmor": 147,
        "SwarmlingWaves": 16,
        "SwarmlingCount": 509,
        "SwarmlingMaxHP": 357,
        "SwarmlingMaxArmor": 112,
        "GiantWaves": 6,
        "GiantCount": 22,
        "GiantMaxHP": 12348,
        "GiantMaxArmor": 140,
        "MonstersBeforeWave12": 130,
        "MarkedMonsterCount": 23,
        "BeaconCount": 6,
        "MonsterNestCount": 4,
        "SnowCount": 1,
        "requirements": [
            ["Field_P2"],
            ["Field_P6"],
            ["Field_P4"],
        ],
    },
    "Z2": {
        "type": "NORMAL",
        "WaveCount": 46,
        "AvailableGems": ["ARMOR_TEARING", "POISON", "SLOWING"],
        "MonsterCount": 796,
        "ReaverWaves": 24,
        "ReaverCount": 302,
        "ReaverMaxHP": 1398,
        "ReaverMaxArmor": 157,
        "SwarmlingWaves": 14,
        "SwarmlingCount": 468,
        "SwarmlingMaxHP": 503,
        "SwarmlingMaxArmor": 147,
        "GiantWaves": 8,
        "GiantCount": 26,
        "GiantMaxHP": 21591,
        "GiantMaxArmor": 221,
        "MonstersBeforeWave12": 198,
        "MonsterNestCount": 1,
        "SnowCount": 1,
        "requirements": [
            ["Field_L1"],
            ["Field_X4"],
            ["Field_K4"],
        ],
    },
    "Z3": {
        "type": "NORMAL",
        "WaveCount": 46,
        "AvailableGems": ["CRITHIT", "ARMOR_TEARING", "SLOWING"],
        "MonsterCount": 312,
        "ReaverWaves": 6,
        "ReaverCount": 73,
        "ReaverMaxHP": 2268,
        "ReaverMaxArmor": 155,
        "SwarmlingWaves": 4,
        "SwarmlingCount": 100,
        "SwarmlingMaxHP": 1121,
        "SwarmlingMaxArmor": 193,
        "GiantWaves": 36,
        "GiantCount": 139,
        "GiantMaxHP": 45195,
        "GiantMaxArmor": 271,
        "MonstersBeforeWave12": 106,
        "MarkedMonsterCount": 3,
        "ManaShardCount": 4,
        "MonsterNestCount": 1,
        "SnowCount": 1,
        "requirements": [
            ["Field_K1"],
            ["Field_K2"],
            ["Field_Z2"],
        ],
    },
    "Z4": {
        "type": "NORMAL",
        "WaveCount": 48,
        "AvailableGems": ["MANA_LEECHING", "BLEEDING"],
        "MonsterCount": 600,
        "ReaverWaves": 15,
        "ReaverCount": 195,
        "ReaverMaxHP": 1412,
        "ReaverMaxArmor": 147,
        "SwarmlingWaves": 10,
        "SwarmlingCount": 317,
        "SwarmlingMaxHP": 632,
        "SwarmlingMaxArmor": 168,
        "GiantWaves": 23,
        "GiantCount": 88,
        "GiantMaxHP": 27111,
        "GiantMaxArmor": 252,
        "MonstersBeforeWave12": 194,
        "MarkedMonsterCount": 33,
        "AbandonedDwellingCount": 7,
        "DropHolderCount": 4,
        "MonsterNestCount": 1,
        "requirements": [
            ["Field_Z3"],
            ["Field_L3"],
            ["Field_L2"],
        ],
    },
    "Z5": {
        "type": "SECRET",
        "WaveCount": 50,
        "AvailableGems": ["MANA_LEECHING"],
        "MonsterCount": 180,
        "GiantWaves": 50,
        "GiantCount": 180,
        "GiantMaxHP": 62632,
        "GiantMaxArmor": 288,
        "MonstersBeforeWave12": 36,
        "MarkedMonsterCount": 3,
        "ManaShardCount": 1,
        "requirements": [
            ["Field_K3"],
            ["Field_G2"],
            ["Field_G1"],
        ],
    },
}
